### PR TITLE
[NEU CS6620] Updated grafana dashboard 

### PR DESCRIPTION
**Pull request by slntpts**
- Regexp was added for cron job into the pod variable
- Added new panels to the dashboard
- Variable component was removed.

### CODE REVIEW

**Comment by slntpts** [comment]
> @slntpts can you run pre-test locally to fix these linting errors? see [here](https://github.com/operate-first/apps/blob/master/contributing.md#tests).

done

**Comment by HumairAK** [comment]
can you squash these commits 1 commit?

**Comment by HumairAK** [comment]
otherwise lgtm

**Comment by HumairAK** [comment]
Can you also include it to this kustomization: https://github.com/operate-first/apps/blob/master/grafana/overlays/moc/smaug/dashboards/cluster-management/kustomization.yaml

**Comment by slntpts** [comment]
I updated the kustomization.yaml and also changed the dashboard name based on the feedback in today's meeting. Please lmk if there is any misunderstanding.

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
