### PR TITLE
include admin for osc-cl1

### PR DESCRIPTION
**Pull request by harshad16**
include admin for osc-cl1
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm

@redmikhail we'd like to extend cluster admin to @harshad16 so he can help with odh maintenance/development on osc-cl1

**Comment by harshad16** [comment]
cc: @redmikhail 
I'm adding myself for cluster-admin, for maintenance

**Pull request merged**
