### PR TITLE
wip: feat: allow access to cluster-logging to open-aiops and thoth groups

### PR DESCRIPTION
**Pull request by tumido**
Possible solution: https://github.com/operate-first/apps/issues/168 https://github.com/operate-first/apps/issues/171

This is a backup option in case this is not an elastic search health problem.

### CODE REVIEW

**Comment by tumido** [comment]
this is just a possible solution. I'm not certain of it. @4n4nd WDYT>

**Comment by 4n4nd** [comment]
> this is just a possible solution. I'm not certain of it. @4n4nd WDYT?

I don't think this might work, as I stated in the issue @eranra already has this role but he still can't access the logs unfortunately :(

**Comment by tumido** [comment]
> I don't think this might work, as I stated in the issue @eranra already has this role but he still can't access the logs unfortunately :(

And as I messaged you and @eranra I think that might be because he didn't try to logging out of Kibana and OpenShift first before trying to access it second time. Because that's the only time the permissions get propagated to the app - when the user is logging in. So he needs to log out first and when he logs in second time it finally picks up the view permissions.

**Comment by eranra** [comment]
@tumido I tried that, so I might have done something wrong in the process of logout/in or this is something else. Maybe we can find time tomorrow to continue are get this to work

**Comment by tumido** [comment]
@eranra I don't think you did anything wrong. We probably need to do something with the RBAC. What namespaces you can see when you log in to the Openshift console/UI?

Based on the docs I think each account is limited to only the indices which maps to projects they do have access to.

https://docs.openshift.com/container-platform/4.3/logging/cluster-logging.html#cluster-logging-about-elasticsearch_cluster-logging

image


But even the things I see in Kibana with my account (I have access to 17 namespaces right now) doesn't seem to capture it all/in the right format:
image

@4n4nd @HumairAK any thoughts?

**Comment by eranra** [comment]
image

**Comment by eranra** [comment]
@tumido ^^^

Also, you should be able to see indexs that start with `infra*` those are from the infrastructure layer

**Comment by tumido** [comment]
@eranra I see only indices that start with `app-*` nothing else. :confused: Somethings wrong there...

**Comment by eranra** [comment]
@tumido I this that this is all connected to premissions ... in other OCP cluster where I am `cluster admin` I see both

**Comment by tumido** [comment]
let me try playing with this. I suspect we need the `cluster-reader` cluster role assigned.

https://github.com/fabric8io/openshift-elasticsearch-plugin/issues/168

**Comment by tumido** [comment]
Closing in favor of https://github.com/operate-first/apps/pull/194

**Pull request closed without merging**
