### PR TITLE
feat: Install Koku operator to Zero cluster

### PR DESCRIPTION
**Pull request by tumido**
Created via https://github.com/operate-first/opfcli/pull/22
Part of: https://github.com/operate-first/support/issues/265

Install and enables operator on Curator cluster

/cc @skanthed

### CODE REVIEW

**Comment by tumido** [comment]
/unhold 

this goes to the Zero cluster instead of the Curator cluster. A consecutive PR adding a new curator team to the Zero cluster + granting them access to koku namespace will follow.

**Comment by HumairAK** [comment]
aside: we don't typically want quotas on operator namespaces yes? 

/lgtm

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
> aside: we don't typically want quotas on operator namespaces yes?

@HumairAK yeah.. I don't know the resource consumption of the operator yet.. but it seems this is a namespace scoped operator and the curator team wants to have access to it.. so.. we may want to set some quota to prevent starving... We'll need to monitor the workloads there and add quota based on the usage. :shrug:

**Pull request merged**
