### PR TITLE
Upgrade openmetadata to 0.12.1

### PR DESCRIPTION
**Pull request by HumairAK**
Resolves:  https://github.com/operate-first/support/issues/1110 https://github.com/operate-first/support/issues/1109

helm chart used is 0.0.39 from here:  https://github.com/open-metadata/openmetadata-helm-charts

### CODE REVIEW

**Comment by HumairAK** [comment]
@erikerlandson / @redmikhail  / @rynofinn  

FYI this is generally what an upgrade to openmetadata looks like. In general we get the latest helm-chart from the release page linked above, and template it then compare the diffs to see the changes made.

**Comment by MichaelTiemannOSC** [comment]
New cross-reference for OM 0.12.1.2 (which should fix data profiling): https://github.com/operate-first/support/issues/1114

**Pull request merged**
