### PR TITLE
feat: Relocate ClusterLogging to a separate app

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/apps/issues/174
Merge together with: https://github.com/operate-first/argocd-apps/pull/58, https://github.com/operate-first/continuous-deployment/pull/97

Relocate an app introduced in https://github.com/operate-first/apps/pull/153

The `Subscription` and `OperatorGroup` are left to stay in `cluster-scope` for now since we need to reach an agreement on how to deal with the operators globally. I will hopefully have the ADR out today. https://github.com/operate-first/blueprint/issues/23 

Has to be rebased after: https://github.com/operate-first/apps/pull/172

@4n4nd here you go! :)

### CODE REVIEW

**Comment by tumido** [comment]
Rebased, you bossy bot...

**Review by hemajv — APPROVED** [review]
:ship:

**Comment by HumairAK** [comment]
isn't /lgtm supposed to add a label? @goern  @harshad16  ?

**Comment by harshad16** [comment]
> isn't /lgtm supposed to add a label? 
I think it should open an issue regarding this: https://github.com/thoth-station/thoth-application/issues/814
will check on this.

**Pull request merged**
