### PR TITLE
new project and admins

### PR DESCRIPTION
**Pull request by cooktheryan**
Signed-off-by: Ryan Cook <rcook@redhat.com>

Closes https://github.com/operate-first/support/issues/506

### CODE REVIEW

**Comment by HumairAK** [comment]
Hey @cooktheryan can you fix the linting errors? You can also run this test locally by following the instructions [here](https://github.com/operate-first/apps/blob/master/contributing.md#tests), it wlil also attempt to auto correct these errors for you.

**Comment by HumairAK** [comment]
@cooktheryan can you also add the namespace to https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml  ? 

See [this onboarding pr](https://github.com/operate-first/apps/pull/1358/files#diff-a6a0c818898dcaa8c31ccd32e1d2004a2fb977c7afc512c89570b9fdc77accbfR79) for an example. This ensures that the namespace resource will be made part of the final kustomize build and is deployed (i.e. created) on the `smaug` cluster via argocd.

**Comment by cooktheryan** [comment]
apologies and thanks @HumairAK for walking me through this

**Comment by HumairAK** [comment]
Npnp! Thanks for making the pr, 
/lgtm

Let's try it out!

**Comment by HumairAK** [comment]
Namespace created here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/training-model 

Let us know if there are any issues! :)

**Pull request merged**
