### PR TITLE
Create argocd-readonly group for read-only access to all resources

### PR DESCRIPTION
**Pull request by larsks**
Add naved (who wants to be able to poke around) and my @redhat.com
account (for testing this out).

### CODE REVIEW

**Comment by HumairAK** [comment]
@larsks can you add this ocp group here: https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/configs/argo_cm/dex.config#L11

this is so people in this group can authenticate via dex.

**Comment by larsks** [comment]
@HumairAK added!

**Comment by HumairAK** [comment]
Just FYI I've encountered some issues in the past with newlines in these config files, though I think that was only for the ENV files, so I think this should be okay. But just a heads up in case things go awry.

Also -- this will require a manual `kustomize build...  | oc apply ... ` etc. to bring changes to the infra cluster. 

/lgtm 
/approve

**Comment by larsks** [comment]
@HumairAK

> Just FYI I've encountered some issues in the past with newlines in these config files

Could you expand on this a bit? Which files in particular, and is there a place where I added newlines in a way that was inconsistent with how the files were already formatted?

> Also -- this will require a manual kustomize build... | oc apply ... etc. to bring changes to the infra cluster.

Why does this require the manual build/apply step? Does argocd not manage itself?

**Comment by HumairAK** [comment]
@larsks currently all of the files in this location: https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/configs 
don't have a newline. These get consumed by the [configmapgenerator](https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/kustomization.yaml#L9).

> Why does this require the manual build/apply step? Does argocd not manage itself? 

Currently no, we can add it, but I'd prefer if we would keep auto sync off (otherwise we would need to turn off auto sync for 3 apps when trying to turn off autosync for any one particular app).

**Comment by HumairAK** [comment]
For more context: Sometime back we had added 1 file per each env var in the configmapgenerator, (like how [these folks](https://github.com/AICoE/aicoe-cd/tree/main/manifests/overlays/prod/configs/argo_cm) do it). and if I recall correctly, adding a new line would get included in the env var, so I had CI ignore newlines in this location and removed them from all these configs to avoid such issues. 

But since then I've moved the env vars in to a while [here](https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/configs/argo_cm/envs), and I don't think these get affected by any newlines in the file.

**Comment by larsks** [comment]
> currently all of the files in this location: https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/configs don't have a newline.

@HumairAK, Now I'm extra confused, because files in that `configs` directory have *lots* of newlines, so I'm not sure what we're talking about.

**Comment by HumairAK** [comment]
bah sorry, I see that I never specified this earlier -- I'm referring to newlines at the end of the file. Woops sorry!

**Pull request merged**
