### PR TITLE
feat(infra): Grant oglok cluster admin

### PR DESCRIPTION
**Pull request by tumido**
@oglok needs a way to manage what ACM addons are installed to his microshift clusters and experiment with it a bit. Since `KlusterletAddonConfig` is a cluster scoped resource kind, he can't touch them. Can we grant him cluster admin access for now?

### CODE REVIEW

**Comment by larsks** [comment]
Seems as if it would be pretty easy to create a clusterrole with appropriate access to klusterlet resources, rather than granting full admin rights.

**Comment by larsks** [comment]
I think that would look like https://github.com/operate-first/apps/pull/1581

**Comment by HumairAK** [comment]
/hold

yeah let's go with #1581 instead @tumido / @oglok  let us know if that works for you

**Comment by larsks** [comment]
Closing in favor of #1581

**Comment by tumido** [comment]
Thank you, #1581 is definitely better!

**Pull request closed without merging**
