### PR TITLE
feature/consistent doc start

### PR DESCRIPTION
**Pull request by larsks**
enforce consistent use of document start marker

### CODE REVIEW

**Comment by larsks** [comment]
Still failing lint:

```
./observatorium/base/instance/loki-routes.yaml
  13:1      warning  found forbidden document start "---"  (document-start)

./odh-manifests/dashboard/overlays/cluster-role/rbac.yaml
  22:1      warning  found forbidden document start "---"  (document-start)

./odh-manifests/prometheus/operator/base/kafka-podmonitors.yaml
  18:1      warning  found forbidden document start "---"  (document-start)
  36:1      warning  found forbidden document start "---"  (document-start)
  54:1      warning  found forbidden document start "---"  (document-start)

./cluster-scope/overlays/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
  20:1      warning  found forbidden document start "---"  (document-start)
  40:1      warning  found forbidden document start "---"  (document-start)

./cluster-scope/overlays/moc/infra/crc-provisioning-vlan.yaml
  23:1      warning  found forbidden document start "---"  (document-start)
  46:1      warning  found forbidden document start "---"  (document-start)

./cluster-scope/overlays/moc/infra/zero-provisioning-vlan.yaml
  23:1      warning  found forbidden document start "---"  (document-start)
  46:1      warning  found forbidden document start "---"  (document-start)

./metallb/base/serviceaccount.yaml
  8:1       warning  found forbidden document start "---"  (document-start)

./metallb/base/rolebinding.yaml
  17:1      warning  found forbidden document start "---"  (document-start)

./metallb/base/role.yaml
  17:1      warning  found forbidden document start "---"  (document-start)

./argocd/base/routes/argocd_server_route.yaml
  18:1      warning  found forbidden document start "---"  (document-start)
  35:1      warning  found forbidden document start "---"  (document-start)
  52:1      warning  found forbidden document start "---"  (document-start)
  69:1      warning  found forbidden document start "---"  (document-start)
```

The ones in `cluster-scope` are my fault and should probably be split
up anyways. I'm unsure of the others, and there doesn't appear to be a
yamllint setting that means "reject the document start marker on line
1 but allow it in between yaml documents".

**Comment by tumido** [comment]
Hm, I wonder @larsks why do we want to have them removed? I'd actually prefer the default yamllint behavior - have them enforced.

**Comment by larsks** [comment]
This was mostly just an experiment. I note that `kustomize` creates documents without the document start marker. I think my take on this is that I don't care enough to pursue it any futher, since I don't want to post-process things generated by `kustomize` any more than I want to fix yamllint to differentiate between "necessary marker separating documents" and "unnecessary start marker at the top of a file". :smile:

**Comment by tumido** [comment]
@larsks yeah... `kustomize` turns a blind eye on various aspect of the not-enforced parts of YAML standards. It's a mess :grin: :shrug:

**Pull request closed without merging**
