### PR TITLE
feat: ODH 1.0.2 z-stream release

### PR DESCRIPTION
**Pull request by tumido**
Change set created via #290 script

Part of https://github.com/operate-first/support/issues/89

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm Nice to see the script in action!

**Comment by HumairAK** [comment]
/lgtm 
Let's merge this tomorrow

**Comment by HumairAK** [comment]
Changes applied

**Comment by HumairAK** [comment]
KFdefs were updated, but some changes require additional steps

**Comment by HumairAK** [comment]
Need to do a rollout for JH to update images in spawner ui

**Comment by 4n4nd** [comment]
New JH rollout was created and tested successfully :+1:

**Pull request merged**
