### PR TITLE
Add security context tufts dcc 6

### PR DESCRIPTION
**Pull request by psmiley2**

### CODE REVIEW

**Comment by tumido** [comment]
FTR this ties back to the Bookinfo deployment on openshift:
https://istio.io/latest/docs/setup/platform-setup/openshift/#privileged-security-context-constraints-for-application-sidecars

The deployments are not starting without these permissions. Please review the CRBs

/cc @HumairAK @4n4nd

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Comment by harshad16** [comment]
Please add  required label `approved` as the ci prow was down , it couldn't add that earlier.
@HumairAK

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
