### PR TITLE
deprecate the thoth servicemonitor as scrapeconfig will be used

### PR DESCRIPTION
**Pull request by harshad16**
deprecate the thoth servicemonitor as scrapeconfig will be used
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: 
- https://github.com/operate-first/apps/pull/828
- https://github.com/thoth-station/thoth-application/issues/1816

### CODE REVIEW

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
