### PR TITLE
Sync klusteraddonconfigs with live.

### PR DESCRIPTION
**Pull request by HumairAK**
This should fix https://github.com/operate-first/apps/issues/952

### CODE REVIEW

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Review by tumido — CHANGES_REQUESTED** [review]
can you add EOLs  please

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by tumido — COMMENTED** [review]
any idea why these 2 clusters (compared to the rest) need a full manifest?

I also don't think we should be tracking the version strings if possible, since that is managed by the operator anyways...

**Pull request closed without merging**
