### PR TITLE
chore: Fix ClusterRole structure

### PR DESCRIPTION
**Pull request by tumido**
Related to: https://github.com/operate-first/apps/pull/178 https://github.com/operate-first/apps/pull/179

### CODE REVIEW

**Comment by 4n4nd** [comment]
Should we keep a single kustomization for the whole `clusterroles` directory?

**Comment by HumairAK** [comment]
@4n4nd  no because we do not want clusters to import all roles, rather we want them to pick and choose which ones they want to include

**Comment by tumido** [comment]
@4n4nd https://github.com/operate-first/apps/blob/master/cluster-scope/README.md

**Comment by HumairAK** [comment]
@4n4nd if the moc kustomization gets over-crowded, we can break into subdirectories in the moc env folder

**Pull request merged**
