### PR TITLE
jupyterlab image for ml-prague-workshop

### PR DESCRIPTION
**Pull request by harshad16**
jupyterlab image for ml-prague-workshop
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

cc: @pacospace

### CODE REVIEW

**Comment by pacospace** [comment]
Related-To: https://github.com/operate-first/support/issues/77

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
Changes applied

**Pull request merged**
