### PR TITLE
fix: ODH Dashboard RBAC to show only prod namespaces

### PR DESCRIPTION
**Pull request by tumido**
Fixes: https://github.com/operate-first/support/issues/132

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

Sorry for the delay in reviewing!

**Review by 4n4nd — APPROVED** [review]

**Comment by tumido** [comment]
applying this requires manual ODH operator restart, redeploying

**Comment by tumido** [comment]
verified, issue fixed :slightly_smiling_face:

**Pull request merged**
