### PR TITLE
feat: Move cluster scope overlays around for multi geo

### PR DESCRIPTION
**Pull request by tumido**
Supporting: https://github.com/operate-first/hetzner-baremetal-openshift/issues/12

Moving cluster-scope overlays around to allow sharing `common` overlay between geos + keeping a MOC specific `common` overlay.

New structure:
```
overlays
├── dev
└── prod
    ├── common
    ├── emea
    │   └── rick        # pulls from /overlays/prod/common
    └── moc
        ├── common      # pulls from /overlays/prod/common
        ├── curator     # pulls from /overlays/prod/moc/common
        ├── infra       # pulls from /overlays/prod/moc/common
        └── zero        # pulls from /overlays/prod/moc/common
```

### CODE REVIEW

**Comment by HumairAK** [comment]
@tumido can you rebase?

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Pull request merged**
