### PR TITLE
[WIP] Add m4d cluster resources to zero cluster.

### PR DESCRIPTION
**Pull request by HumairAK**
Resolves https://github.com/operate-first/support/issues/192

### CODE REVIEW

**Comment by HumairAK** [comment]
/hold 

due to size

**Comment by tumido** [comment]
> due to size, and room for discussion

Should we be reviewing this or is this still WIP?

**Comment by HumairAK** [comment]
@tumido - apologies, it was only after making the PR I realized the cluster roles are a bit too generous. Let's wait on https://github.com/operate-first/support/issues/192#issuecomment-829601647.

**Comment by HumairAK** [comment]
closing this for now, while we wait for an update from m4d

**Pull request closed without merging**
