### PR TITLE
Add notebook to explore onboarding data and possible metrics

### LINKED ISSUE #1957: Create an exploration type of notebook to see what data we have available w.r.t onboarding applications, and what are some possible metric definitions.
Furthers: https://github.com/operate-first/support/issues/571

### PR DESCRIPTION
**Pull request by chauhankaranraj**
Closes #1957 

Marked as WIP because PR data is not being collected correctly (all dates are `1970-01-19`) by the MI tool. So we're unable to include any PR related data in the analysis.

### CODE REVIEW

**Comment by SamoKopecky** [comment]
@chauhankaranraj Is this PR ready for review since its no longer WIP?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj Is this PR ready for review since its no longer WIP?

Yep, it's good to review :)

**Comment by SamoKopecky** [comment]
Please review this PR.

Pinging @HumairAK since he created the issue that is resolved by this PR.

**Comment by durandom** [comment]
@schwesig please take a look, this is good stuff for your metrics exploration
The rendered notebook can be viewed at https://github.com/chauhankaranraj/apps/blob/add-onboarding-eda/notebooks/onboarding-eda.ipynb

**Pull request closed without merging**
