### PR TITLE
kubevirt-hyperconverged migration to smaug

### PR DESCRIPTION
**Pull request by Gregory-Pereira**

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
Missing subscription:

https://github.com/operate-first/apps/blob/674b89efe636aad473bcec1cbbf1d2a7cf1421f1/cluster-scope/overlays/prod/moc/zero/kustomization.yaml#L117

https://github.com/operate-first/apps/blob/674b89efe636aad473bcec1cbbf1d2a7cf1421f1/cluster-scope/overlays/prod/moc/zero/kustomization.yaml#L183

https://github.com/operate-first/apps/blob/674b89efe636aad473bcec1cbbf1d2a7cf1421f1/cluster-scope/overlays/prod/moc/zero/kustomization.yaml#L107

https://github.com/operate-first/apps/blob/674b89efe636aad473bcec1cbbf1d2a7cf1421f1/cluster-scope/overlays/prod/moc/zero/kustomization.yaml#L50

**Comment by larsks** [comment]
I don't think we want to install the CNV operator on smaug unless there is an actual demand for it.

**Comment by HumairAK** [comment]
> I don't think we want to install the CNV operator on smaug unless there is an actual demand for it.

agreed

**Pull request closed without merging**
