### PR TITLE
feat:Added openshift-pipelines operator for rick

### PR DESCRIPTION
**Pull request by mimotej**
SSIA, resolves https://github.com/operate-first/support/issues/340 .

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
Nit, please use https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

PR content looks good :+1:

**Review by tumido — COMMENTED** [review]
/lgtm

/cc @4n4nd

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by 4n4nd** [comment]
synced and applied :+1:

**Pull request merged**
