### PR TITLE
Update image and description for Elyra AIDevSecOps Tutorial

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/approve

**Comment by pacospace** [comment]
@tumido when starting server and looking for the image, I don't see the image updated actually, can someone look into this?

**Comment by 4n4nd** [comment]
@pacospace can you check again?

**Comment by pacospace** [comment]
> @pacospace can you check again?

Now is there @4n4nd!! Thanks!! what happened?

**Comment by 4n4nd** [comment]
@pacospace we have the autosync for this argocd app disabled, so it needed to be applied manually. Once applied manually, it worked.

**Comment by pacospace** [comment]
> @pacospace we have the autosync for this argocd app disabled, so it needed to be applied manually. Once applied manually, it worked.

Thanks for the explanation!! ❤️

**Pull request merged**
