### PR TITLE
feat(catalog): Redefine grafana component following a new ADR

### PR DESCRIPTION
**Pull request by SamoKopecky**
Part of [operate-first/service-catalog#55](https://github.com/operate-first/service-catalog/issues/55)

~~Blocked by: [operate-first/service-catalog#78](https://github.com/operate-first/service-catalog/pull/78)~~

## Changed
Redefine grafana as a fully defined entity following the new [ADR 0022](https://github.com/operate-first/blueprint/pull/109), which includes adding:
- `grafana`, `dex` APIs
- `smaug`, `sqlite` resources
- `grafana-public`, `grafana-oauth` components
- `dex`, `grafana` systems

Add labels to grafana operator deployments since they are needed for the k8s plugin.

Move grafana documentation to `docs` folder because `MkDocs` doesn't like when the source `.md` files are in the same directory as the `mkdocs.yaml` file. See the error here:

```
ERROR    -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory of the config file. Use a child directory instead so that the 'docs_dir' is a sibling of the config file.
ERROR    -  Config value: 'site_dir'. Error: The 'site_dir' should not be within the 'docs_dir' as this leads to the build directory being copied into itself and duplicate nested files in the 'site_dir'.(site_dir:
            '/home/skopecky/git/apps/docs/content/grafana/site', docs_dir: '/home/skopecky/git/apps/docs/content/grafana')
Aborted with 2 Configuration Errors!

```

### CODE REVIEW

**Comment by SamoKopecky** [comment]
No longer blocked.

/unhold

**Comment by SamoKopecky** [comment]
Waiting for #2205 to merge.
/hold

**Comment by SamoKopecky** [comment]
#2205 is merged, unblocking.

/unhold

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
