### PR TITLE
Upgrade infra cluster to 4.6.21

### PR DESCRIPTION
**Pull request by larsks**
How do we want to handle updates on the infra cluster w/r/t scheduling?

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm
/hold

**Comment by tumido** [comment]
@larsks I think we can add this to the Monday management window and do it along with the zero cluster upgrade. WDYT?

**Review by tumido — APPROVED** [review]
/approve

**Comment by harshad16** [comment]
There is hold label added to this PR. 
@tumido just letting you know.

**Comment by tumido** [comment]
Yup, we should plan on a new maintenance window for this, we missed the planned one. Thank @harshad16 

Wanna do it today/tomorrow @larsks @HumairAK ?

**Comment by HumairAK** [comment]
@tumido let's do it tomorrow if @larsks can confirm. Let's send an email out as well: https://github.com/operate-first/SRE/blob/master/incident-management/incident-management-procedure.md#cluster-version-upgrade-notice-template

**Comment by tumido** [comment]
i thought the same, thanks @HumairAK :+1:

**Comment by larsks** [comment]
Tomorrow is fine. I'm not sure I would even bother with an email, since this isn't an end-user facing cluster. The only people who need to be aware of the state of the infra cluster are on `#ops`.

**Comment by HumairAK** [comment]
@4n4nd as oncall do you want to send the e-mail out?

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
