### PR TITLE
Adding namespace, configmaps and rbac for kyverno

### PR DESCRIPTION
**Pull request by screeley44**
Adding namespace, configmaps and rbac for kyverno

related issue: https://github.com/operate-first/support/issues/488 

@harshad16 @HumairAK - I started this PR to help move this along, not sure I did it right, I'm basing it off of this yaml installation

https://raw.githubusercontent.com/kyverno/kyverno/release-1.5/definitions/release/install.yaml 

I guess the next steps are to figure out where I create the ServiceAccount, CRD and Deployment? I was poking around but didn't find anything that jumped out at me?

### CODE REVIEW

**Comment by HumairAK** [comment]
> **Scott Creeley wrote:**
> Humair Khan Harshad - I created the following issue and start of a PR for kyverno (image verification after signing) namespace, rbac, etc...
> <https://github.com/operate-first/support/issues/488>
> <https://github.com/operate-first/apps/pull/1404>
> 
> no idea if I did this correct?
> 
> **Humair Khan wrote:**
> hey Scott Creeley nice, I think this looks good, everything seems in its right place except maybe the configmap, though I'll need to take a deeper look -- might not get to it today, but can take a look tomorrow morning/early afternoonish
> 
> **Humair Khan wrote:**
> Harshad Anand Sanmukhani if you are around ^
> 
> **Scott Creeley wrote:**
> thanks Humair Khan - let me know how I can help
> 
> **Humair Khan wrote:**
> I see you asked about SA/deployments/crd's etc.,
> 
> so the CRD's will also go in the cluster-scope directory, if you search for the apiextensions api group,
> 
> but SA/Deployment/Configmaps, basically anything you can typically deploy as a project admin, they will go in a separate directory in the root of `apps` repo, these will be deployed as a separate ArgoCD application
> 
> **Humair Khan wrote:**
> for example we deploy this operator manually as welll: <https://github.com/operate-first/apps/tree/master/odh-operator>
> 
> all the cluster resources for it are in the `cluster-scope` directory, but you can see that we put the deployment/SA/etc. in the `base` then pull it down to the `overlays/moc/smaug` folder
> 
> **Humair Khan wrote:**
> any thing cluster specific will go in the `overlays`
> 
> **Humair Khan wrote:**
> so probably the configmaps in this case (unless they are also super generic I suppose :man-shrugging: )
> 
> **Humair Khan wrote:**
> then you need an argocd app to deploy this path, add this application declaratively here, you can see the other manifests there for an idea of how to populate it, I think it's relatively self explanatory, but we also have some <https://www.operate-first.cloud/apps/content/argocd-gitops/add_application.html|docs> here for it.
> <https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first>
> 
> **Humair Khan wrote:**
> _really need to document this_
> 

_Transcript of Slack thread: https://operatefirst.slack.com/archives/C01RMPVUUK1/p1638478085167200?thread_ts=1638478085.167200&cid=C01RMPVUUK1_

**Comment by screeley44** [comment]
@harshad16 @HumairAK - I removed the configmaps per our slack conversation, and added in the CRDs to the apiextensions group. I think this one is ready for review.

Moving forward I will create 2 PRs (if I understand correctly)
1. Add base kyverno app in root apps/ dir where I will put the deployment, SA, and services
2. Add this to ArgoCD as an app deployment

Sound like a plan?

**Review by harshad16 — CHANGES_REQUESTED** [review]
lgtm

crds are to be also added to the kustomization.yaml
under here: https://github.com/operate-first/apps/pull/1404/files#diff-a6a0c818898dcaa8c31ccd32e1d2004a2fb977c7afc512c89570b9fdc77accbfR29

**Comment by harshad16** [comment]
> 1. Add base kyverno app in root apps/ dir where I will put the deployment, SA, and services
> 2. Add this to ArgoCD as an app deployment
> 
> Sound like a plan?

Yes that would be correct.
PR 1 for the app and PR2 for setup of argocd app for deployment.

**Comment by screeley44** [comment]
added CRDs to the overlay kustomization for smaug

**Comment by HumairAK** [comment]
hrmm I haven't really been following this project closely, but taking a look at the cluster roles, this controller seems to be asking for a lot of permissions, for example: 

```
  - apiGroups:
      - '*'
    resources:
      - namespaces
      - networkpolicies
      - secrets
      - configmaps
      - resourcequotas
      - limitranges
    verbs:
      - create
      - update
      - delete
      - list
      - get
```

The `name: kyverno:webhook` role also seems excessive...but I'm not too familiar with the cert resources. Can these roles be toned down? For instance why does a validator need such cluster-wide write level permissions? 

Also I think this should get more eyes @larsks  @4n4nd 
And maybe further discussion can be had here: https://github.com/operate-first/apps/pull/1404 
As this is effectively deciding how we ought to manage k8s resource validation for smaug.

**Comment by screeley44** [comment]
> Apologies but I haven't really been following this project closely. I just took some time to read over kyverno and had some questions. Taking a closer look at the cluster roles, this controller seems to be asking for a lot of permissions, for example:
> 
> ```
>   - apiGroups:
>       - '*'
>     resources:
>       - namespaces
>       - networkpolicies
>       - secrets
>       - configmaps
>       - resourcequotas
>       - limitranges
>     verbs:
>       - create
>       - update
>       - delete
>       - list
>       - get
> ```
> 
> The `name: kyverno:webhook` role also seems excessive...but I'm not too familiar with the cert resources. Can these roles be toned down? For instance why does a validator need such cluster-wide write level permissions?
> 
> Also I think this should get more eyes @larsks @4n4nd And maybe further discussion can be had here: #1404 As this is effectively deciding how we ought to manage k8s resource validation for smaug (not against it, but would be interested in others' thoughts).

cc
@lukehinds @cooktheryan

Let me talk with Luke to see what he thinks and maybe we can tone some of this down

**Comment by lukehinds** [comment]
I don't know kyverno to well, but i suspect a lot could be removed. would it be to laborious to comment each one out and see if it causes an issue?

**Comment by jimcadden** [comment]
> I don't know kyverno to well, but i suspect a lot could be removed. would it be to laborious to comment each one out and see if it causes an issue?

Since we are only using a sub-component of kyverno (the validator), how about we remove the just write-level permission, or anything @HumairAK sees as problematic, and see if it works?

**Comment by larsks** [comment]
I have some concerns about the motivation for this PR that I've left in a [commented on #488](https://github.com/operate-first/support/issues/488#issuecomment-1010255036).

**Comment by cooktheryan** [comment]
https://github.com/operate-first/continuous-delivery/pull/28 in place. If merged we can remove this

**Comment by codificat** [comment]
/close
as we are going with `cosigned` instead (#1560)

**Pull request closed without merging**
