### PR TITLE
In onboarding.sh change display-name annotation to description

### PR DESCRIPTION
**Pull request by 4n4nd**
Related https://github.com/operate-first/opfcli/issues/41

### CODE REVIEW

**Comment by larsks** [comment]
Rather than fixing onboarding.sh we should just remove it.

**Comment by 4n4nd** [comment]
unfortunately [some of our docs](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md#adding-namespaces) still need to be updated. I think until we update the docs to use opfcli, we should keep the script.

**Comment by larsks** [comment]
Then maybe this PR should update the docs *and* remove the script. I am highly in favor of using this as an excuse to get rid of the script, rather than continuing to maintain two separate implementations of this functionality.

**Comment by 4n4nd** [comment]
afaik @HumairAK was working on updating the docs, but he isn't around today. I thought until then we could add this minor fix.

**Comment by tumido** [comment]
Let's resolve the discussion at https://github.com/operate-first/opfcli/issues/41 first.

**Comment by 4n4nd** [comment]
it was decided to not maintain the `onboarding.sh` script. closing

**Pull request closed without merging**
