### PR TITLE
Add Pep to balrog cluster admins, replacing Anand

### PR DESCRIPTION
**Pull request by codificat**
This is to add myself as cluster admin for the balrog cluster (where Thoth prod runs).

Removing Anand from the list too.

### Additional context

The trigger for this request was for me to get access to argo workflows running on the cluster, as I currently do not have access to them. 

I know cluster-admin is overkill for that, but... on one hand I could not locate specific group(s) for that specific access (happy to get pointers), and on the other hand I thought it could be handy anyway for other tasks :innocent:

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
thanks :100:

**Comment by durandom** [comment]
@codificat can you rebase the PR to make prow happy?

**Comment by codificat** [comment]
> @codificat can you rebase the PR to make prow happy?

Rebased, and prow is happy.

For complete happiness, can I have my *lgtm* label back?

**Comment by Gregory-Pereira** [comment]
you can.
/lgtm
/approve

**Pull request merged**
