### PR TITLE
add docs for volsync to gitops jupyterbook

### PR DESCRIPTION
**Pull request by dystewart**

### CODE REVIEW

**Comment by dystewart** [comment]
This PR is in response to issue #1617

**Comment by dystewart** [comment]
@larsks Interesting I thought the main commit message would be `add docs for volsync to gitops jupyterbook` seeing as I squashed down the commit with the message `numerous precommit fixes`.
Is this something I can fix with a rebase?

**Comment by larsks** [comment]
@dystewart you can just `git commit --amend`, edit your commit message, and then `git push -f`.

**Comment by dystewart** [comment]
@larsks  I have amended the commit to reflect the more descriptive message

**Pull request merged**
