### PR TITLE
doubling kubeval check memory limits and requires

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Temporarily addresses: https://github.com/operate-first/apps/issues/2288
/cc @HumairAK 
/cc @mimotej

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
Not sure why this test is failing, logs ([available here](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-ci-prow/pods/0509f7a4-23dd-11ed-b423-0a580a82052d/logs) state that:
```
Checking changes in range 240605ab587cdd44eb1bf64b54855b4c39c2e60e..eb2322361b550d28de704acae039ed236c6ef30e only.
Aborting due to errexit on line 11. Exit code: 1
Aborting due to errexit on line 11. Exit code: 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-08-24T18:46:23Z"}
```

**Comment by mimotej** [comment]
> Not sure why this test is failing, logs ([available here](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-ci-prow/pods/0509f7a4-23dd-11ed-b423-0a580a82052d/logs)) state that:
> 
> ```
> Checking changes in range 240605ab587cdd44eb1bf64b54855b4c39c2e60e..eb2322361b550d28de704acae039ed236c6ef30e only.
> Aborting due to errexit on line 11. Exit code: 1
> Aborting due to errexit on line 11. Exit code: 1
> {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-08-24T18:46:23Z"}
> ```
@Gregory-Pereira this fail is expected because you are changing only `.prow.yaml` and script check if there are changes in manifests which are related to clusters, it finds none and grep fails. Therefore these errors can be safely ignored

**Comment by HumairAK** [comment]
> Therefore these errors can be safely ignored

@mimotej as this is a valid pr, and expected type of change, we should note that the ci check should account for this and not fail -- can you capture this in an issue?

**Comment by mimotej** [comment]
> > Therefore these errors can be safely ignored
> 
> @mimotej as this is a valid pr, and expected type of change, we should note that the ci check should account for this and not fail -- can you capture this in an issue?

@HumairAK Done :heavy_check_mark: https://github.com/operate-first/apps/issues/2294

**Pull request merged**
