### PR TITLE
adding myself to osc cluster admins for ml-kubeflow-pipelines access

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
more osc acccess stuffs.
/cc @HumairAK 
/cc @redmikhail

### CODE REVIEW

**Comment by HumairAK** [comment]
@redmikhail, @Gregory-Pereira is part of the operate-first SRE team (you have probably seen him a bunch of times in meetings), he's helping @MichaelTiemannOSC debug issues with kubeflow, for easier access for this (and future issues) let's give him cluster admin to the os-climate clusters

**Comment by HumairAK** [comment]
ignoring ci due to ongoing ci issues, and also self merging due to time constraints

**Comment by MichaelTiemannOSC** [comment]
To clarify, it's not me who needs cluster access, it's @Gregory-Pereira.  I want to remain well-removed from any admin roles.

**Comment by HumairAK** [comment]
image

**Pull request merged**
