### PR TITLE
Update odh to 1.0.5

### PR DESCRIPTION
**Pull request by HumairAK**
See release change log here: https://github.com/opendatahub-io/odh-manifests/releases

I've also updated the operator image along with this patch. 

All kfdefs were updated in this repo, included user provisioned.

### CODE REVIEW

**Comment by HumairAK** [comment]
@harshad16 @isabelizimm  your kfdef will be updated to point to the newer odh-manifests.

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by HumairAK** [comment]
FYI the subsequent release updates will only be done to the operate-first kfdefs, and we will let users update their kfdefs (via PR's) as they see fit.

**Pull request merged**
