### PR TITLE
request for namespace required for continuous integration components

### PR DESCRIPTION
**Pull request by harshad16**
namespace requirements for continuous integration components
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: #118

### CODE REVIEW

**Comment by HumairAK** [comment]
This lgtm, but same as my comment [here](https://github.com/operate-first/apps/pull/118#issuecomment-762459000)
@tumido  wdyt?

**Comment by tumido** [comment]
I'd say [this](https://github.com/operate-first/apps/pull/118#issuecomment-762784375). :smile: Let's merge this, unblock Harshad and rebase my PR after that.

**Review by tumido — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
changes applied

**Comment by harshad16** [comment]
> changes applied

unfortunately, I can't  view the namespaces opf-ci-pipelines and opf-ci-prow 
can it be because of the groups?

**Comment by HumairAK** [comment]
taking a look

**Comment by HumairAK** [comment]
resolved -- seems I must have messed up somewhere when applying the changes, looking forward to having argocd manage this instead.

**Pull request merged**
