### PR TITLE
Re organize odh kfdefs to separate app

### PR DESCRIPTION
**Pull request by HumairAK**
Furthers: https://github.com/operate-first/apps/issues/466 

This PR does the following: 
1. Moves all non override manifests to the `kfdef` app 
2. Also removes the grafana dashboards overlay from the grafana kfdef (since it was removed from [here][1]) 

I haven't added/removed the way things are deployed, just moved them around for now. I'm not sure if we _only_ want `kfdefs` in this kfdef app, or also the accompanying manifests (like jh imagestreams, pvcs, routes etc.). But we can discuss options (and save that for the later pr possibly). 

You'll notice now that it's a lot more clear how we are extending `odh` in the `odh-manifests` folder. The structure is identical to the source repo, any additionas would emulate this structure. The paths for overrides are also easier to reason about when adding them to the kfdef, for example: [old][2] vs [new][3]. 

The newer version matches the default `kfdef` [version here][4] with a prefix of 'odh-manifests/' added.

[2]: https://github.com/operate-first/apps/blob/master/odh/base/monitoring/kfdef.yaml#L31
[3]: https://github.com/HumairAK/apps/blob/reorg_kfdefs/kfdefs/base/monitoring/kfdef.yaml#L31
[4]: https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift.yaml#L75

[1]: https://github.com/operate-first/apps/pull/539/files

### CODE REVIEW

**Comment by HumairAK** [comment]
hrmm, this is going to require us to update https://github.com/operate-first/toolbox/blob/master/scripts/test-kustomize-build#L20 

I'll first let folks review this before sending that pr in.

**Review by tumido — COMMENTED** [review]
hey.. this is huge! This is a huge cleanup work! :+1: Awesome stuff. :+1: 

/lgmt

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Pull request merged**
