### PR TITLE
Install Horreum operator to mwperf-horreum namespace

### PR DESCRIPTION
**Pull request by rvansa**
Created through

```
opfcli install-operator horreum-operator community-operators -n mwperf-horreum -s -c alpha
```

@HumairAK Please review.

I hope that as a project admin I'll have the necessary privileges to create a CR brought by the operator (if not I'll try file another PR).

### CODE REVIEW

**Comment by HumairAK** [comment]
@rvansa one additional step not covered by the cli yet, you need to add these to the specific cluster as well: 
https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/zero/kustomization.yaml#L5 

Fyi: we try to keep this alphabetically sorted for human readability.

**Review by tumido — CHANGES_REQUESTED** [review]
@rvansa thank you for a PR! :slightly_smiling_face: 

Please see comment above by @HumairAK ^ you need to do one additional step - include the new `base` resources into an `overlay`.

**Comment by rvansa** [comment]
@HumairAK @tumido Thanks for pointing this out, I've added the requested changes.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
