### PR TITLE
Update ArgoCD to v2.0.1, and update docs.

### PR DESCRIPTION
**Pull request by HumairAK**
Context: https://github.com/operate-first/apps/issues/498

Also updated upgrade docs, and threw in a script for updating updating the cluster resources. Some minor changes to the dev deployment as well.

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

nice script! :+1:

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by anishasthana — APPROVED** [review]
/lgtm

**Comment by HumairAK** [comment]
announced for tomorrow 10 am est: https://github.com/operate-first/SRE/issues/267

**Pull request merged**
