### PR TITLE
Add Xskipper to pyspark packages in spark2.4 based images

### PR DESCRIPTION
**Pull request by oshritf**
FYI: @erikerlandson @durandom

### CODE REVIEW

**Comment by HumairAK** [comment]
@oshritf does this require a review from the people you tagged? or can this be merged?

**Comment by oshritf** [comment]
can be merged, thanks!

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
