### PR TITLE
Update Kfdefs to 1.0.4

### PR DESCRIPTION
**Pull request by HumairAK**
See release details [here](https://github.com/opendatahub-io/odh-manifests/releases)

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/hold
/approve

Let's update it one by one as usual. Unhold when ready

**Review by 4n4nd — APPROVED** [review]

**Pull request merged**
