### PR TITLE
add opf-ci-test-pods namespace

### PR DESCRIPTION
**Pull request by goern**
/sig devops

### CODE REVIEW

**Review by anishasthana — CHANGES_REQUESTED** [review]
Could you clean up the commits please?

**Review by harshad16 — COMMENTED** [review]
Add the namespace in here as well https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/kustomization.yaml
rest lgtm to me

**Comment by goern** [comment]
thanks for the comments

**Review by tumido — CHANGES_REQUESTED** [review]
I think you forgot to list the namespace in [`cluster-scope/overlays/moc/kustomization.yaml`](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/kustomization.yaml), otherwise it won't get deployed to MOC

**Comment by tumido** [comment]
@goern why did you close this PR and opened this one instead? https://github.com/operate-first/apps/pull/225

The 221 one is much better, the 225 won't work... I think you just wanted to add a single line to this PR and squash the commits for Anish. :smile:

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
Changes applied

**Pull request merged**
