### PR TITLE
feat: Upgrade ACM operator to 2.5

### PR DESCRIPTION
**Pull request by SamoKopecky**
SSIA

### CODE REVIEW

**Comment by tumido** [comment]
/hold

@SamoKopecky Before merging please make an announcement on Slack and keep an eye on the upgrade process please.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by schwesig** [comment]
> /hold
> 
> @SamoKopecky Before merging please make an announcement on Slack and keep an eye on the upgrade process please.
275865

other than that:
/lgtm
/approve

**Review by schwesig — APPROVED** [review]

**Comment by SamoKopecky** [comment]
> /hold
> 
> @SamoKopecky Before merging please make an announcement on Slack and keep an eye on the upgrade process please.

I'll send out an announcement but I don't have permissions to access some resources, for example https://argocd.operate-first.cloud/applications/acm-infra, so I might need a little help with monitoring things.

**Pull request merged**
