### PR TITLE
feat: Add ray-odh-intagration

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/support/issues/97

### CODE REVIEW

**Comment by erikerlandson** [comment]
should I be a member of new ray group?

**Comment by anishasthana** [comment]
@erikerlandson there isn't an existing group that you'd fit into.

**Comment by tumido** [comment]
@erikerlandson yes, you are added in this Rh, though not in the `base`, but in the `overlays/moc-base`, because any membership is environment specific. :slightly_smiling_face: 

your username is encrypted and hidden in this line:
https://github.com/operate-first/apps/pull/298/files#diff-b11c43cf31cacbb543e8a26c0fe394790dc637bbce9eef64cf2f9fde634f4155R8

**Comment by erikerlandson** [comment]
@tumido @HumairAK  What is the cluster url I should use to log into my new `ray-odh-integration` namespace?

**Comment by HumairAK** [comment]
@erikerlandson  you can find your namespace [here](https://console-openshift-console.apps.cnv.massopen.cloud/k8s/cluster/projects/ray-odh-integration) -- let us know if it works, you should have admin access.

**Comment by erikerlandson** [comment]
@HumairAK  I'm in - will test it more tomorrow!

**Pull request merged**
