### PR TITLE
[MOC] Added a new user in lab-cicd group

### PR DESCRIPTION
**Pull request by acidonper**
Added a new user in lab-cicd group.

I added this new user using my private GPG key and I am not sure this process worked fine. Could you check that before applying the merge?

Thanks!

### CODE REVIEW

**Comment by HumairAK** [comment]
@4n4nd

**Comment by 4n4nd** [comment]
@acidonper since you encrypted it with your private key, we won't be able to decrypt it. Could you please use [this sops config](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/common/.sops.yaml) to encrypt the file?

While you are at it, could you also rebase your branch so that we have a clean commit?

Thanks!

**Comment by 4n4nd** [comment]
Related https://github.com/operate-first/support/issues/113

**Comment by HumairAK** [comment]
@acidonper can you squash this into a single commit?

**Comment by acidonper** [comment]
Sorry @HumairAK, I think that it is ok right now

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
