### PR TITLE
add grafana-public dashboard

### PR DESCRIPTION
**Pull request by schwesig**
solves https://github.com/open-services-group/scrum/issues/40

### CODE REVIEW

**Comment by schwesig** [comment]
dashboard
snapshot
[grafana.operate-first.cloud/dashboard/snapshot/2I4k71DpSz3wvIWvvnT2eSi08XyVH71N](https://grafana.operate-first.cloud/dashboard/snapshot/2I4k71DpSz3wvIWvvnT2eSi08XyVH71N)

**Comment by Gregory-Pereira** [comment]
I haven't used Grafana snapshots before but Im pretty sure it implies that successfully created this resource in a Grafana instance which is pretty much all the validation we need. Just in case I am going to create it as a dry run and then delete it so argocd can apply the changes.

**Comment by Gregory-Pereira** [comment]
@schwesig, when loading it in, it says "not valid json" are we sure that this is constructed properly? I think you may be missing a closing parenthasy or something.

**Comment by Gregory-Pereira** [comment]
Never mind, it looks good.
/lgtm
/approve

**Comment by Gregory-Pereira** [comment]
This will fail being synced and argocd as smaug grafana and public smaug grafana are competing over who owns the admin credentials resource. I will introduce a pr to fix this.

**Pull request merged**
