### PR TITLE
feat: Onboard CCX to openshift-insights namespace

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/support/issues/242

### CODE REVIEW

**Comment by tumido** [comment]
/hold

to verify user list

**Review by 4n4nd — COMMENTED** [review]
/lgtm
the `openshift-insights` namespace already existings for the insights-operator

**Comment by tumido** [comment]
> `the openshift-insights` namespace already existings for the insights-operator

@4n4nd yes :+1: It's present on the cluster by default, I just needed to grant them access to it since they are the developers of that operator.

**Comment by tumido** [comment]
/unhold

users added per specification in https://github.com/operate-first/support/issues/242#issuecomment-845029635. Ready for review

/cc @HumairAK @4n4nd

**Review by HumairAK — APPROVED** [review]
/lgtm

**Pull request merged**
