### PR TITLE
script to descale workloads

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
decomissioning script
/cc @cooktheryan

### CODE REVIEW

**Comment by goern** [comment]
why dont we do this via PR that change the argocd configuration and have argocd do the job? @Gregory-Pereira

**Comment by Gregory-Pereira** [comment]
@goern , already have a PR (https://github.com/operate-first/apps/pull/2780) to remove auto-sync. We wanted to approach it this way because we do not want to delete all manifests in case a team complains and OCTO approves them to spin up their workloads again, so this method removes compute while leaving the structure in place. What we do plan to remove: routes, services, deployments, statefulsets, replicasets, daemonsets, etc. What we don't plan to remove: configmaps, secrets, etc. We have a post spindown meeting to evaluate if this strategy is effective enough to reduce our costs with management.

**Comment by goern** [comment]
I don't get that. The plan communicated was to decommission the smaug cluster. Is that still the plan? So cleaning up the apps repo would make most sense, as it is reflecting the desired state. Removing objects from a cluster manually and turning off Gitops feels suboptimal and leaves the gitops repo in a state that needs to be considered unclean, so restarting or deploying on a different infrastructure would involve a cleanup of the repo anyway.

**Comment by cooktheryan** [comment]
@goern the strategy is hopefully one last safety net for people to realize the environment is powering down. It's a "soft" last warning before shutdown. This way if the project is something incredibly important to RH, a university or etc that it can be synced again and an immediate migration plan can be established.

**Comment by goern** [comment]
:evilgrin: `revert commit` you said? :)

**Pull request closed without merging**
