### PR TITLE
Include oef_openclimate in catalog

### PR DESCRIPTION
**Pull request by evanp**
This adds the OEF OpenClimate database to the catalog. It doesn't provide the database password, which I will send directly to Erik.

### CODE REVIEW

**Comment by evanp** [comment]
The schema is here:

https://github.com/Open-Earth-Foundation/OpenClimate-Schema/tree/main/SQL

**Comment by evanp** [comment]
@durandom Is there something I need to do here? There is some missing data due to the database password being secret.

**Review by tumido — COMMENTED** [review]
/ok-to-test
/retest

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
@evanp unfortunately we had some CI issues lately. It was acting up a bit. It should be resolved now. I'm approving your PR now and it should be merged shortly. :slightly_smiling_face:

**Pull request merged**
