### PR TITLE
Added ababar to cluster admin

### PR DESCRIPTION
**Pull request by ajinkyababar**

### CODE REVIEW

**Comment by HumairAK** [comment]
see: https://github.com/operate-first/common/pull/55#issuecomment-1013356124
can you change this to your github handle, thanks!

**Comment by HumairAK** [comment]
@hpdempsey can you or someone else from curator confirm that they can be given cluster admin to the curator cluster? thanks!

**Comment by ajinkyababar** [comment]
> see: [operate-first/common#55 (comment)](https://github.com/operate-first/common/pull/55#issuecomment-1013356124) can you change this to your github handle, thanks!

Done

**Comment by gagansk** [comment]
> @hpdempsey can you or someone else from curator confirm that they can be given cluster admin to the curator cluster? If not please advise what sort of access they need.
> 
> thanks!

@HumairAK You can add @ajinkyababar to the Curator cluster admin group. He is a co-op who will be working with the Curator team for the next 6 months.

**Review by gagansk — APPROVED** [review]
LGTM!

**Comment by 4n4nd** [comment]
/ok-to-test

@ajinkyababar can you squash these commits to one?

**Comment by ajinkyababar** [comment]
> /ok-to-test
> 
> @ajinkyababar can you squash these commits to one?

Done

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
