### PR TITLE
onboarding boatroackers

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses https://github.com/operate-first/support/issues/524

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
Normally I would let the team owner onboard however this is helpful for me when updating my onboard automation.
/cc @HumairAK

**Comment by larsks** [comment]
Please include information in the PR description in the commit message (this way we can see it when reviewing the commit log).

**Comment by Gregory-Pereira** [comment]
> Please include information in the PR description in the commit message (this way we can see it when reviewing the commit log).

Got it, Ill make sure to include more relevant information in the commit messages

**Pull request merged**
