### PR TITLE
Update OpenShift Pipelines at Jerry to version 1.8

### PR DESCRIPTION
**Pull request by rbo**
PR to update OpenShift Pipelines to Version 1.8 at Jerry cluster.

Discussed here: https://operatefirst.slack.com/archives/C01RF4SPNDD/p1675620390285109

### CODE REVIEW

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Comment by rbo** [comment]
@schwesig looks like your `/approve` is ignored.

**Comment by durandom** [comment]
@rbo we recently discovered that something is wrong with the ingress loadbalancer on jerry. Just letting you know. Dont know how much user facing http apps your project involves

**Pull request merged**
