### PR TITLE
Add keylime application base

### PR DESCRIPTION
**Pull request by mpeters**
Also add moc/morty overlays

### CODE REVIEW

**Comment by HumairAK** [comment]
/ok-to-test 

@mpeters to have ci auto run on your prs you can [request an invite to the org.](https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md#become-a-github-member) (simple one line change). 

Also the apps repo is for manifests that will be deployed by our Argocd, is that your intention? And do you require your own argocd project to manage it via argocd?

**Comment by HumairAK** [comment]
@mpeters pre-commit failures, you can run this test locally https://github.com/operate-first/apps/blob/master/contributing.md#tests

**Comment by codificat** [comment]
To add some additional context here, this is related to https://github.com/AICoE/summit-2022-octo-keynote/issues/6

> Also the apps repo is for manifests that will be deployed by our [Argocd instance](https://argocd.operate-first.cloud/applications?proj=&sync=&health=&namespace=&cluster=&labels=), is that your intention?

I believe so, yes. The namespace and access were added recently to Argocd via #1815

> And do you require your own argocd project to manage it via argocd?

The ArgoCD app would go here I believe: https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/applications/envs/octo

So, in addition to the `keylime/*` manifests added in the PR so far, the ArgoCD ones (to be added) would go there.

Does that make sense?

**Comment by HumairAK** [comment]
> The ArgoCD app would go here I believe: https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/applications/envs/octo
So, in addition to the keylime/* manifests added in the PR so far, the ArgoCD ones (to be added) would go there.

Argocd apps are organized by the clusters in which they will be deployed in (see [here](https://www.operate-first.cloud/apps/content/argocd-gitops/add_application.html) ). 

So you want to create a directory [here](https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/applications/envs/emea/morty) after your argocd project which seems to be: `octo-ushift-dev`.  Create the argocd application in this directory and set `destination.name` to `morty`.

**Comment by codificat** [comment]
@mpeters is this still relevant?

**Comment by durandom** [comment]
@mpeters do you still intent to deploy this? If so we should move over to the jerry cluster, since morty is no more

**Comment by mpeters** [comment]
No, this won't be necessary anymore. We don't currently need an install of keylime to serve other services outside. Instead, we'll be doing a different setup for keylime to guard the operate first cluster.

**Pull request closed without merging**
