### PR TITLE
⚡ removing the workshop related stuff #clarety

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@b4mad.net>

### CODE REVIEW

**Comment by goern** [comment]
pre-commit warning arise from wrong comment indention

/cc @Gregory-Pereira

**Comment by durandom** [comment]
Why would we want to remove this? Isn't this a good starting point for hosting workshops on a cluster?

**Comment by goern** [comment]
ja it is, I just wanted to declutter this repo, as it feels a little complex. and touching 85 files to deploy a workshop environment appeared strange to me.

**Pull request merged**
