### PR TITLE
update Operate First logo on GitOps Docs

### PR DESCRIPTION
**Pull request by schwesig**
updating to the new logo

### CODE REVIEW

**Comment by HumairAK** [comment]
/hold 
wait -- the sizes are different, does this matter?

**Comment by schwesig** [comment]
@HumairAK 
> /hold wait -- the sizes are different, does this matter?

- size for favicon: must be a multiple of 48px x 48px, following google SEO guidelines, 
[Define Website Favicon for Search Results - Google Developers](https://developers.google.com/search/docs/appearance/favicon-in-search#:~:text=Your%20favicon%20must%20be%20a,looks%20good%20at%20that%20resolution.)
  - This one is 144 x 144 (3 x 48)n and looks like this locally build:
image
- size for the logo was taken from the operate-first.cloud, luckily fits kind the width and looks good
image

> 
> @schwesig can you build the docs and see if it runs fine, and looks as expected? [operate-first.cloud/apps/CONTRIBUTING.html](https://www.operate-first.cloud/apps/CONTRIBUTING.html)

- yes I did already, forgot to post the pictures/ statement here
  - altogether looks like this
  image

**Comment by schwesig** [comment]
/remove do-not-merge_hold

see
> heart
> 
> /approve /lgtm

**Pull request merged**
