### PR TITLE
Add black flake people to data-science group.

### PR DESCRIPTION
**Pull request by martinpovolny**
We plan to use the data-science group to work on the black flake project and have access to black flake-related resources.

So I am adding all the people from the black flake meeting.

FYI: @MichaelClifford 

Context: next steps will be to 

1) add a black-flake app to operatefirst/argocd-apps overlays/moc/data-science and have it request a CEPH bucket.
2) the manifests will be located in https://github.com/aicoe-aiops/ocp-ci-analysis manifests directory.

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
changes applied :+1:

**Pull request merged**
