### PR TITLE
Adding new pipeline schemas for osc-cl2

### PR DESCRIPTION
**Pull request by caldeirav**
These are the new schemas for ESSD, DERA and WRI data pipelines

/cc @HumairAK @erikerlandson

### CODE REVIEW

**Comment by caldeirav** [comment]
For information @MichaelTiemannOSC once the schemas a created I can merge the revised WRI-GPPD pipeline with metadata ingestion

**Comment by MichaelTiemannOSC** [comment]
Great news!  If Hurricane Ian doesn't take my power, I will have a fun weekend learning from what you have done!!

**Comment by HumairAK** [comment]
@caldeirav you have some whitespace errors from pre-commit, can you correct them? You can also run pre-commit locally and it will fix these for you automatically: https://github.com/operate-first/apps/blob/master/contributing.md#linting

**Comment by caldeirav** [comment]
@HumairAK I have now fixed this and base checks are completed successfully. Need review and approval please, and a restart of Trino when deployed.

**Review by erikerlandson — APPROVED** [review]

**Pull request merged**
