### PR TITLE
Move overlays around

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/apps/issues/306
Resolves: https://github.com/operate-first/blueprint/issues/28

A commit per application. This PR is huge, sorry for that, it's mainly moving files around though.

### CODE REVIEW

**Comment by tumido** [comment]
Note: prow is not testing this PR, because of https://github.com/operate-first/SRE/issues/62

http://tekton-dashboard-tekton-pipelines.apps.cnv.massopen.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/aicoe-pipelinerun-5d5v6
https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/opf-ci-pipelines/pods/aicoe-pipelinerun-5d5v6-pr-configuration-776vq-pod-pxphx/events
image

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
