### PR TITLE
OKD-89: feature: adds a new argoCD app to deploy okd tekton pipeline

### PR DESCRIPTION
**Pull request by aguidirh**
This argoCD app will allow the automatic deployment of resource of okd release pipelines when a new commit is merged on main branch.

### CODE REVIEW

**Comment by LorbusChris** [comment]
@HumairAK @durandom could you take a look?

**Comment by harshad16** [comment]
@LorbusChris and @aguidirh 
Active development on operate-first is halted.
Please take a look at the announcement in slack.
https://operatefirst.slack.com/archives/C01RT0NNCP7/p1679428090163579

**Comment by LorbusChris** [comment]
I like the idea of continuing the collaboration over on NERC/MOC :)

/lgtm
/test pre-commit

**Comment by larsks** [comment]
I have been asked by @hpdempsey to force-merge this pr. After this we will not accepting any further pull requests against this repository.

**Pull request merged**
