### PR TITLE
Move monitoring rbac to cluster-scope

### PR DESCRIPTION
**Pull request by 4n4nd**
Remove monitoring rbacs from odh and observatorium apps
Enable monitoring rbac components in Opf, Thoth and Argocd namespaces

Related #136

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
I think you also wanted to remove the component usage from ODH moc overlay:

```
$ grep -r "components/rbac" odh/overlays/moc
odh/overlays/moc/argo/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/dashboard/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/datacatalog/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/jupyterhub/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/kafka/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/monitoring/kustomization.yaml:  - ../../../components/rbac
odh/overlays/moc/superset/kustomization.yaml:  - ../../../components/rbac
```

And from observatorium:
```
$ grep -r "components/rbac" observatorium
observatorium/overlays/moc/kustomization.yaml:  - ../../components/rbac
```

**Comment by 4n4nd** [comment]
> I think you also wanted to remove the component usage from ODH moc overlay:
> 
> ```
> $ grep -r "components/rbac" odh/overlays/moc
> odh/overlays/moc/argo/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/dashboard/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/datacatalog/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/jupyterhub/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/kafka/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/monitoring/kustomization.yaml:  - ../../../components/rbac
> odh/overlays/moc/superset/kustomization.yaml:  - ../../../components/rbac
> ```
> 
> And from observatorium:
> 
> ```
> $ grep -r "components/rbac" observatorium
> observatorium/overlays/moc/kustomization.yaml:  - ../../components/rbac
> ```

I think that's a different rbac
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-rolebinding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: operate-first
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
 ```

**Comment by tumido** [comment]
Ah. I got confused... yes. those are a bit different, though they are redundant as well, since we apply the namespace admin role at the `cluster-scope/namespaces`  anyways. I'll clean that up tomorrow. :slightly_smiling_face:

**Review by tumido — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]
Love it, thanks @4n4nd

**Pull request merged**
