### PR TITLE
[Telemetry WG] Tufts project: Setup namespace for dcc group 6

### PR DESCRIPTION
**Pull request by psmiley2**
Created namespace for group 6 dcc, Deploy and collect workflow-centric traces from microservice applications. @tumido

### CODE REVIEW

**Comment by tumido** [comment]
We're not able to install the cluster today, so I'm gonna stall this ticket a bit. Sorry guys. We've hit some unexpected issues (if curious, the progress is tracked here: https://github.com/open-infrastructure-labs/ops-issues/issues/21)

**Comment by tumido** [comment]
@psmiley2 can you and the rest of the team please log in into this cluster using the MOC SSO please?

https://console-openshift-console.apps.zero.massopen.cloud/

I'll collect your identities from the cluster and update the group in here for you. :slightly_smiling_face:

**Comment by psmiley2** [comment]
We have all made an account!

**Comment by tumido** [comment]
Thank you @psmiley2 ! I've added you all to the group + myself. All set.

/unhold

/cc @HumairAK @4n4nd can I ask you guys for a review, please?

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by 4n4nd** [comment]
@tumido can you fix the linter error in your commit?

**Comment by tumido** [comment]
already on it :+1: @4n4nd  :smile:

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by tumido** [comment]
rebased and new keys added

/unhold

**Comment by HumairAK** [comment]
@tumido can you squash some of these commits?

**Comment by tumido** [comment]
I was waiting if anybody notices... I was counting on @anishasthana  :smile:

**Comment by anishasthana** [comment]
Ha, I happened to miss this PR. ++ @HumairAK  :-)

**Comment by tumido** [comment]
@anishasthana @HumairAK done!

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
