### PR TITLE
Test kustomize build fix

### PR DESCRIPTION
**Pull request by goern**

### CODE REVIEW

**Comment by HumairAK** [comment]
Hrmm I've just tried this out and I think there's going to be an issue with the overrides folder, where the `kustomization.yaml` is incomplete: 

Example: 
```
checking ./odh/base/datacatalog
checking ./odh/base/dashboard/overrides/overlays/cluster-role
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../../base': evalsymlink failure on '/home/hukhan/projects/github/operate-first/apps/odh/base/dashboard/overrides/base' : lstat /home/hukhan/projects/github/operate-first/apps/odh/base/dashboard/overrides/base: no such file or directory"
	* loader.New error: "error loading ../../base with git: url lacks host: ../../base, dir: evalsymlink failure on '/home/hukhan/projects/github/operate-first/apps/odh/base/dashboard/overrides/base' : lstat /home/hukhan/projects/github/operate-first/apps/odh/base/dashboard/overrides/base: no such file or directory, get: invalid source string: ../../base"

```

Can we ignore the `overrides` directories? Example: 

```
odh/base/dashboard/overrides
odh/base/jupyterhub/overrides
odh/base/monitoring/overrides
```

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by goern** [comment]
> Can we ignore the `overrides` directories? Example:

done.

**Pull request merged**
