### PR TITLE
add memory size options to os-climate cluster

### PR DESCRIPTION
**Pull request by erikerlandson**
xref: https://github.com/os-climate/os_c_data_commons/issues/65

### CODE REVIEW

**Comment by erikerlandson** [comment]
Note, the original PR requested increased filesystem size: I do not know how to configure the PVC to change file size.

**Comment by erikerlandson** [comment]
I see that there are some per-user specifications for PVCs, for example:
kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/michaelclifford.yaml

1) Is there a way to change the default PVC resource request?
2) Is there a way make PVC resource request part of the singleuser profiles, along with memory and cpu?

cc @vpavlin

**Comment by 4n4nd** [comment]
@erikerlandson you should be able to set the default pvc size in the JH configmap ([example](https://github.com/operate-first/apps/blob/master/odh-manifests/zero/jupyterhub/base/jupyterhub-configmap.yaml))

**Comment by erikerlandson** [comment]
cc @redmikhail

**Comment by HumairAK** [comment]
@erikerlandson current cpu/mem usage here: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/cluster/nodes?orderBy=asc&sortBy=Memory

**Comment by erikerlandson** [comment]
@HumairAK  if looks ok to you, can we merge?

**Pull request merged**
