### PR TITLE
Update ODH to 1.0.6 z-release.

### PR DESCRIPTION
**Pull request by HumairAK**
Also updated the script to only update kfdefs in odh/observatorium folder.

### CODE REVIEW

**Review by tumido — DISMISSED** [review]
Please merge and apply https://github.com/operate-first/apps/pull/458 first and then run again. Ot should update the `odh-operator` image as well.

**Comment by HumairAK** [comment]
@tumido good catch, done.

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
