### PR TITLE
wip: feat: Enable to view cluster monitoring for anybody

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/support/issues/163

### CODE REVIEW

**Review by larsks — APPROVED** [review]

**Comment by 4n4nd** [comment]
this is what the role looks like:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-view
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
```

**Comment by tumido** [comment]
I'm gonna need to do my homework on this role... let's hold this for a moment please.

/wip

**Comment by HumairAK** [comment]
closing this pr as it's stale, if still needed please re-open/rebase etc.

**Pull request closed without merging**
