### PR TITLE
feat: Deploy Keycloak 

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/apps/issues/789
Required by: https://github.com/operate-first/argocd-apps/pull/170

- [x] Move Dex from `auth` folder to `dex` and from `opf-auth` to `dex` namespace
- [x] Install Keycloak operator
- [x] Declare Keycloak instance in `keycloak` folder and deploy it to `keycloak` namespace

### CODE REVIEW

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by HumairAK** [comment]
@tumido infra cluster doesn't have a storageclass configured: 
image

**Pull request merged**
