### PR TITLE
Add user suppathak to the odh-admin group

### PR DESCRIPTION
**Pull request by 4n4nd**
SSIA

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Review by tumido — APPROVED** [review]
/lgtm
/approve

Is there any need to keep this on hold? @4n4nd

**Review by tumido — CHANGES_REQUESTED** [review]
Actually... :smile: :facepalm:  yes.. please rebase on https://github.com/operate-first/apps/pull/842 no need for ksops here anymore.

**Comment by 4n4nd** [comment]
@tumido yeah we are waiting for suppathak to go through the openshift tutorials before merging this.

**Comment by HumairAK** [comment]
AFAIK this is not needed anymore

**Pull request closed without merging**
