### PR TITLE
Add asanmukh as Jupyterhub admin

### PR DESCRIPTION
**Pull request by 4n4nd**
only one user can be added as admin for some reason, so I will manually add @HumairAK and @tumido as admins.

### CODE REVIEW

**Comment by HumairAK** [comment]
I think this means you're the official admin and hence responsible for all future jupyterhub issues. 

/lgtm

**Comment by HumairAK** [comment]
actually is this something better done in an overlay for zero environment? and don't you want to encrypt it?

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
