### PR TITLE
feat: ODH 1.0.10 z-stream release

### PR DESCRIPTION
**Pull request by tumido**
SSIA, manual, because the script failed due to https://github.com/operate-first/apps/pull/556

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
Release notes: https://github.com/opendatahub-io/odh-manifests/releases/tag/v1.0.10

**Comment by HumairAK** [comment]
Deployed Kfdefs, ODH operator redeployed

**Comment by HumairAK** [comment]
Strimzi required manual upgrade approval

**Comment by HumairAK** [comment]
Manual upgrade approval was due to: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-jupyterhub/imagestreams/jupyterhub-img

**Comment by HumairAK** [comment]
Kafka back to green, inbound message rate back up

**Comment by HumairAK** [comment]
JupyterHub did not update automatically, doing a manual rollout

**Comment by tumido** [comment]
> Manual upgrade approval was due to: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-jupyterhub/imagestreams/jupyterhub-img

Correction: Due to https://github.com/operate-first/apps/pull/559

**Comment by HumairAK** [comment]
JH on stage good, rolled out on prod, also good

**Comment by HumairAK** [comment]
Now that ODH reconciles changes, we noticed we were overwriting some manifests via argocd. This resulted in argocd fighting with odh, fix was given here: https://github.com/operate-first/apps/pull/560

**Pull request merged**
