### PR TITLE
Give ray users permissions to jupyterhub ns.

### PR DESCRIPTION
**Pull request by HumairAK**
Related #336

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by erikerlandson** [comment]
@HumairAK   I can see most cluster resources but I tried creating a RayCluster test-CR and getting:

```
$ oc apply -f ray-test-cluster-cr.yaml
...
from server for: "ray-test-cluster-cr.yaml": rayclusters.cluster.ray.io "ray-cluster-smoketest" is forbidden:
    User "eerlands@redhat.com" cannot get resource "rayclusters" in API group "cluster.ray.io" in the namespace "opf-jupyterhub"
```

A role-binding to the `ray-operator` Role in the same namespace (for my username) might work, but maybe there is some other preferred way

**Comment by HumairAK** [comment]
@erikerlandson I submitted a PR that adds an aggregated role which will allow project admins to deploy a ray CR -- would this work?

**Comment by erikerlandson** [comment]
@HumairAK yes, that works - I can create RayCluster objects and the operator spins up a ray cluster :+1:

**Pull request merged**
