### PR TITLE
Add thoth-station SA in `opf-monitoring`

### PR DESCRIPTION
**Pull request by 4n4nd**
give thoth-station access to opf-monitoring

Resolves https://github.com/operate-first/support/issues/267

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Comment by harshad16** [comment]
@4n4nd  thank you for the PR
i was wondering based on your comments in the slack thread
would it be more convenient if we create a SA in our namespace and then we provide rolebinding ?

**Comment by harshad16** [comment]
actaully it feel like better way.
/lgtm

**Pull request merged**
