### PR TITLE
Install Service Mesh operator

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/support/issues/111

Installs Service Mesh and it's prerequisites according to:
https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/installing-ossm.html

- [x] Install ElasticSearch operator (already available)
- [x] Install Jaeger operator
- [x] Install Kiali operator
- [x] Install Service mesh operator

### CODE REVIEW

**Comment by tumido** [comment]
I need to test if it doesn't try to manage any of the Kubeflow resources before we apply this :slightly_smiling_face:

**Comment by tumido** [comment]
/cc @HumairAK @4n4nd 

I've rebased this PR and included it to base only. The intention is to deploy service mesh to the Hetzner Rick cluster once available - we can have subscriptions merged and ready when Rick is connected. https://github.com/operate-first/hetzner-baremetal-openshift/issues/12

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
