### PR TITLE
fix: Use Grafana/Prometheus as an ODH ocomponent

### PR DESCRIPTION
**Pull request by tumido**
Fixes: #79, #49, https://github.com/operate-first/odh-dashboard/issues/2  #44

Fixes multitude problems with monitoring deployment:

- The prometheus instance was deployed twice - once by us once by ODH https://github.com/operate-first/apps/issues/79
- The `grafana-operator` ODH component was not used, therefore it wasn't showing up on the dashboard #49 https://github.com/operate-first/odh-dashboard/issues/2 
- Since have no control on whey `kfdef` is processed by the operator, we ran into sync issues with Argo CD when deploying CRDs which definitions are deployed via ODH. https://github.com/operate-first/apps/issues/44

This simple reorg of the monitoring manifests layout moves all our custom manifests into ODH overrides

1. Add [`grafana-operator` component](https://github.com/opendatahub-io/odh-manifests/tree/master/grafana) and overrides it's `grafana.yaml` `Grafana` resource with our custom one, instead of deploying it aside of ODH.
2. Override [`prometheus-operator` component](https://github.com/opendatahub-io/odh-manifests/tree/master/prometheus/operator)'s `prometheus.yaml` - the `Prometheus` instance - which solves the 2 Prometheus instances issue.
3. Remove the unnecessary route, since we already had 2 routes pointing to the exact service

Since we would deploy the `grafana-operator` now, we'll also get [all the default dashboards](https://github.com/opendatahub-io/odh-manifests/tree/master/grafana/grafana/base) it comes with it, which should solve https://github.com/operate-first/SRE/issues/11 as well.

### CODE REVIEW

**Comment by tumido** [comment]
/hold

Please try building the manifests for yourself and check it properly

You can use this kfdef:
```
---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kfctl.kubeflow.io/force-delete: "false"
  name: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
    - kustomizeConfig:
        repoRef:
          name: opf
          path: odh/base/monitoring/overrides/prometheus-operator
      name: prometheus-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/cluster
      name: grafana-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/grafana
      name: grafana-operator
    - kustomizeConfig:
        repoRef:
          name: opf
          path: odh/base/monitoring/overrides/grafana-operator
      name: grafana-operator
  repos:
    - name: manifests
      uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v0.9.0"
    - name: opf
      uri: "https://github.com/tumido/apps/tarball/fix-grafana-odh-component"
  version: v0.9.0

```

**Review by anishasthana — APPROVED** [review]

**Comment by tumido** [comment]
I actually think I've introduced the second prometheus myself instance in the apps restructure PR... Anyways. This fixes it.😁

**Comment by anishasthana** [comment]
Ha, I didn't realise you'd held it too.

**Comment by anishasthana** [comment]
Prometheus and Grafana deploye without issue with the ODH operator.

**Review by HumairAK — APPROVED** [review]
Yeah this is good, this way we're basically using the prom we were deploying to instead have odh deploy it. LGTM

**Comment by tumido** [comment]
FYI: if we later need to deploy additional resources that depends on the ODH's deployed CRDs, we can do it in the override by defining additional overlay, the same way we do that in the `odh-dasboard` [here](https://github.com/operate-first/apps/tree/master/odh/base/dashboard/overrides/overlays/cluster-role)

**Comment by anishasthana** [comment]
I'd put it on hold initially as Tom had tagged a few people for reviews. @hemajv  hasn't looked at it yet.  Tom had actually put it on hold before me anyways, so... :shrug: . I'm good to merge whenever.

**Review by 4n4nd — APPROVED** [review]
LGTM :ship:

**Comment by HumairAK** [comment]
tbh I think this is a pretty straightforward change, w/ more than enough approvals, let's go with it
/unhold

**Pull request merged**
