### PR TITLE
Remove Jh instance from ds-ml-worklows-ws kfdef

### LINKED ISSUE #1493: Remove unused Jupyterhub instance
Hey there 👋

This is a Slack discussion you wanted me to capture.

> **Anand Sanmukhani wrote:**
> *Remove the `ds-ml-workflows-ws` Jupyterhub instance*
> 
> **Anand Sanmukhani wrote:**
> Karan Chauhan Shrey Anand
> 
> **Anand Sanmukhani wrote:**
> If the Jupyterhub instance in the ds namespace is not being used, can we just remove it?
> 
> **Michael Clifford wrote:**
> I'm pretty sure that should be fine
> 
> **Michael Clifford wrote:**
> this is an instance originally used for one of isabell's demo's
> 
> **Michael Clifford wrote:**
> now its mainly used as a seldon serving namespace
> 
> **Shrey Anand wrote:**
> We are seeing a resource crunch due to the JH instance so the services are not being deployed.
> 
> **Shrey Anand wrote:**
> We should remove it if it's no longer required
> 
> **Anand Sanmukhani wrote:**
> awesome
> 
> **Anand Sanmukhani wrote:**
> i'll create the PR for it
> 
> **Shrey Anand wrote:**
> thanks :slightly_smiling_face:
> 
> **Michael Clifford wrote:**
> :thumbsup:
> 
> **Karan Chauhan wrote:**
> great, thank you!
> 
> **Michael Clifford wrote:**
> Shrey I think there is also resource crunch in that namespace due to a larger than needed default resource request from the model services.
> 
> **Michael Clifford wrote:**
> did you and Karan discuss using smaller resource requests for the model services?
> 
> **Shrey Anand wrote:**
> oh yeah, was addressing that issue and redeploying a service with less resources but it could not find mem for a pod.
> 
> **Shrey Anand wrote:**
> <https://github.com/aicoe-aiops/ocp-ci-analysis/issues/463>
> 

_Transcript of Slack thread: https://operatefirst.slack.com/archives/C01RMPVUUK1/p1641499136015300?thread_ts=1641499136.015300&cid=C01RMPVUUK1_

### PR DESCRIPTION
**Pull request by 4n4nd**
Resolves #1493

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
/LGTM but why are we saving the URI of the repo as a tarball?

**Review by Gregory-Pereira — APPROVED** [review]
/LGTM but why are we saving the URI of the repo as a tarball?

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Comment by 4n4nd** [comment]
> /LGTM but why are we saving the URI of the repo as a tarball?

kfctl downloads the repo as a tarball before it applies the manifests

**Pull request merged**
