### PR TITLE
Added a publicly visible personal sandbox for @MichaelTiemannOSC

### PR DESCRIPTION
**Pull request by MichaelTiemannOSC**
… that can be used for ingestion and open metadata prototyping.

Signed-off-by: MichaelTiemannOSC <mtiemann@os-climate.org>

### CODE REVIEW

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC   The CL2 trino instance has been updated.  You should now be able to `create schema if not exists mdt_sandbox` and begin using it

**Comment by MichaelTiemannOSC** [comment]
Alas: `TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_DATABASE_LOCATION_ERROR, message="Database 'mdt_sandbox' location does not exist: file:/opt/hive/warehouse/mdt_sandbox.db", query_id=20220706_092458_38543_hwebh)`

Which means that this naive code is wrong:

`create_schema = engine.execute(f"create schema if not exists {ingest_schema}")`

Or it is wrong to create an engine like this before the schema is actually created:

`engine = osc.attach_trino_engine(env_var_prefix="TRINO", catalog=ingest_catalog, schema=ingest_schema, verbose=True)`

Or...?

**Comment by MichaelTiemannOSC** [comment]
I changed my code to this:

```
create_schema = engine.execute(f"""CREATE SCHEMA osc_datacommons_dev.mdt_sandbox                             
 AUTHORIZATION USER michaeltiemannosc                                  
 WITH (                                                                
    location = 's3a://osc-datacommons-s3-bucket-dev02/data/mdt_sandbox.db' 
 )
""")
create_schema.fetchall()
```

and it works.

**Pull request merged**
