### PR TITLE
Disable sending logs Elasticsearch and send logs to Loki

### PR DESCRIPTION
**Pull request by 4n4nd**
Update Log Forwarding to send logs to Kafka instead of Elasticsearch
Update Vector Config to consume logs from kafka and push to Loki
Add grafana dataources for the newly added logging tenants (infra/audit)
Also add an oauth proxy for observatorium grafana. Only accounts that have access to the `openshift-logging` namespace can view infra and audit logs.

### CODE REVIEW

**Comment by 4n4nd** [comment]
/hold
need to test something

**Comment by 4n4nd** [comment]
/unhold
tested working with infra and audit logs

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
