### PR TITLE
fix a tiny typo

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

just a tiny fix of a typo

### CODE REVIEW

**Review by larsks — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve

**Comment by HumairAK** [comment]
Let's use this pr as a test to get ci stuff working, do not manually merge.

**Comment by harshad16** [comment]
@HumairAK  you can merge this one manually. 
i have open #347  for testing

**Pull request merged**
