### PR TITLE
updated namespace yaml to set label

### PR DESCRIPTION
**Pull request by psmiley2**

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/approve

**Comment by HumairAK** [comment]
Can you squash the commits to one?

**Comment by HumairAK** [comment]
Err 2 different people >_>

**Review by HumairAK — APPROVED** [review]
Okay let's get this in, but aim to keep such prs to 1 commit.

**Comment by tumido** [comment]
@HumairAK yep, I' just fixing the pre-commit, sorry... We're in a live sessions right now :smile:

**Pull request merged**
