### PR TITLE
fix: Address feedback on #358 Contribution doc update 

### PR DESCRIPTION
**Pull request by tumido**
SSIA

Fixes: https://github.com/operate-first/blueprint/issues/49

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
@tumido sorry for not adding it in on the previous PR -- could we add a point to the check-list saying "Ensure that the pre-commit check passes"?

**Comment by tumido** [comment]
@anishasthana done

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
