### PR TITLE
feat: move slack-first namespace to smaug

### PR DESCRIPTION
**Pull request by mimotej**
Moving slack-first namespace from zero to smaug.
Related: https://github.com/operate-first/argocd-apps/pull/187

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by tumido — CHANGES_REQUESTED** [review]
actually, can you please also rename the `slack-first/overlays/moc/zero` to smaug?

**Comment by 4n4nd** [comment]
@mimotej can you rebase?

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
