### PR TITLE
servicemonitor setup for thoth-station component monitoring

### PR DESCRIPTION
**Pull request by harshad16**
servicemonitor setup for thoth-station component monitoring
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/operate-first/apps/issues/108

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
The files look good to me. Any reason we are holding?

**Comment by HumairAK** [comment]
I'm guessing this needs the additional rbac, @4n4nd  can you consult on this

**Comment by 4n4nd** [comment]
> I'm guessing this needs the additional rbac, @4n4nd can you consult on this

I have already added the rbac to all thoth and opf namespaces in the rbac cleanup PR: https://github.com/operate-first/apps/pull/138

**Comment by 4n4nd** [comment]
> The files look good to me. Any reason we are holding?

I have this and it works, but I think @harshad16 wants to do some minor changes to this before this is merged.
I'll just change this PR to WIP

**Review by tumido — APPROVED** [review]

**Comment by harshad16** [comment]
This pull -request is already has been approved.
I will not change anything in this. Instead, move my other changes to another PR. 

/unhold.

**Pull request merged**
