### PR TITLE
Add GeoEducator to OKD WG group

### PR DESCRIPTION
**Pull request by LorbusChris**
Give @GeoEducator access to the `okd-wg` namespace

### CODE REVIEW

**Comment by LorbusChris** [comment]
cc @GeoEducator

**Comment by LorbusChris** [comment]
@GeoEducator re: https://github.com/okd-project/okd-coreos-pipeline/pull/16#issuecomment-1274981669, you'll be able to use the `okd-wg` namespace here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/okd-wg

You shouldn't be able to break anything there :) 
Once this merges, you'll get an invite email from GH for joining the `operate-first` org here. You must accept that before you'll be able to access the cluster.

**Comment by GeoEducator** [comment]
Ok

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
