### PR TITLE
Onboarding Redhat-Impact team

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses: https://github.com/operate-first/support/issues/527.

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
@metaversed

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by HumairAK** [comment]
FYI I think for the future for onboarding a short commit message like "Onboarding x project" is probably sufficient, don't need to list each resource that was added :)

**Comment by Gregory-Pereira** [comment]
> FYI I think for the future for onboarding a short commit message like "Onboarding x project" is probably sufficient, don't need to list each resource that was added :)

Understood. Lars was rightfully telling me that in general my commits are too vague, but I think well known and documented processes like onboarding are an exception.

**Comment by Gregory-Pereira** [comment]
> you can always add more descriptions to any commit messages, I don't think anyone will fault you for that even if it's for onboarding, but it's good to keep the _subject line_ short and minimal, then leave a space, and expand in the body.

Got it :+1:

**Pull request merged**
