### PR TITLE
feat: Convert routes with cert to acme-operator

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/support/issues/280

### CODE REVIEW

**Comment by tumido** [comment]
let's hope ArgoCD or odh operator won't be deleting the certs, since they are not part of the spec... :confused:

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
/unhold

only dashboard should propagate automatically :slightly_smiling_face:

**Pull request merged**
