### PR TITLE
Add okd-team group

### PR DESCRIPTION
**Pull request by LorbusChris**
Adds a group for use by Red Hatters working on OKD

/cc @durandom 

/cc @aleskandro
/cc @cheesesashimi
/cc @dmueller2001
/cc @lmzuccarelli
/cc @LorbusChris
/cc @sandrobonazzola
/cc @sherine-k
/cc @travier
/cc @vrutkovs

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Review by travier — APPROVED** [review]

**Review by aleskandro — APPROVED** [review]

**Comment by HumairAK** [comment]
Just a heads up, when adding to a cluster like smaug, this group will need to also be included [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/common/kustomization.yaml).

**Pull request merged**
