### PR TITLE
fix: Missing storage class in datacatalog

### PR DESCRIPTION
**Pull request by tumido**
Fixes: https://github.com/operate-first/apps/pull/250#issuecomment-777744745

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
changes applied, kfdef sync'd

**Pull request merged**
