### PR TITLE
feat: Enable GH alert receiver for Cluster Monitoring on MOC Infra

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/SRE/issues/56
Depends on: https://github.com/operate-first/argocd-apps/pull/100

~Requires some more testing first.~

Tested against quicklab https://console-openshift-console.apps.testtcoufal.lab.upshift.rdu2.redhat.com/
and https://github.com/tumido/test/issues repo

### CODE REVIEW

**Comment by tumido** [comment]
Ready to be reviewed, tested here: https://github.com/tumido/test/issues

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm

**Pull request merged**
