### PR TITLE
docs: Update docs for CNV/Zero migration

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/apps/issues/306, https://github.com/operate-first/SRE/issues/108

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by oindrillac — APPROVED** [review]
:+1:

**Comment by tumido** [comment]
@HumairAK any reason to hold this?

**Comment by HumairAK** [comment]
@tumido these routes don't become active until after migration -- I figured we'd merge it then, if you would like to merge it now then go for it, not a big deal!

**Comment by tumido** [comment]
@HumairAK Gotcha... Well, I don't mind either way. I guess I just wanted to keep the list of "PRs-to-merge" short because I'm lazy. :smirk:

**Comment by HumairAK** [comment]
Yeah that's fine, let's merge it
/unhold

**Pull request merged**
