### PR TITLE
Add 10Gi PVCs to kafka and zookeeper

### LINKED ISSUE #467: Add Storage to Kafka deployment
We need to add PVCs to the kafka deployment, rn all messages are ephemeral so in case of pod restarts all messages get deleted.

### PR DESCRIPTION
**Pull request by 4n4nd**
Resolves #467 
Related #465  

After this is merged, the kafka resource needs to be recreated. This will result in tls certs being reset.
cc @harshad16

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

can we get this in at the end of the day.

**Review by tumido — COMMENTED** [review]
/lgtm
/hold

**Comment by 4n4nd** [comment]
> /lgtm
> 
> can we get this in at the end of the day.

yeah sure :+1: 
We can merge this in now and recreate the Kafka CR later in the day

**Comment by harshad16** [comment]
/unhold
thanks for waiting

**Pull request merged**
