### PR TITLE
add and remove templates to reflect current state of thoth-messaging

### PR DESCRIPTION
**Pull request by KPostOffice**
New messages present in thoth.messaging and adviser-rerun has been removed

### CODE REVIEW

**Review by harshad16 — CHANGES_REQUESTED** [review]
Thanks :100: 
can you update this in https://github.com/operate-first/apps/blob/79377aa5661c0a08642c76a6ff48e1ee46baa4c9/odh-manifests/kafka/overlays/topics/kustomization.yaml

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
