### PR TITLE
Rework owners file to utilize both approvers and reviewers

### PR DESCRIPTION
**Pull request by anishasthana**
Full context can be found at https://github.com/open-infrastructure-labs/ops-issues/issues/16

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
I'll follow this up with easing of the branch protections. Can we get a confirmation that those being included in this list will be able to review the prs in this repo? if not then we should remove them from this list. 

/hold

**Comment by anishasthana** [comment]
@harshad16 @martinpovolny @hemajv  are you comfortable with being reviewers on this repository?

**Comment by hemajv** [comment]
> @harshad16 @martinpovolny @hemajv are you comfortable with being reviewers on this repository?

yes :+1:

**Comment by harshad16** [comment]
> are you comfortable with being reviewers on this repository?

yes :+1:

**Comment by goern** [comment]
> I'll follow this up with removing of the branch protections. Can we get a confirmation that those being included in this list will be able to review the prs in this repo? if not then we should remove them from this list.

Anyone who is a contributor to this repo can do a review, and /lgtm on a PR, this will note merge. If we want the grant the same ability via GitHub UI, the member must at least have 'triage' accecc. 

is that what you are looking for?

**Comment by goern** [comment]
seeAlso https://github.com/thoth-station/thoth-application/pull/805

**Review by tumido — APPROVED** [review]

**Comment by anishasthana** [comment]
@goern @HumairAK was referring to the reviewers themselves having _time_ to review PRs. I.e we could add Hema to the reviewer list, but if she doesn't have time to review PRs it doesn't make sense for her to be there.

**Comment by HumairAK** [comment]
Sorry if I was unclear, @anishasthana interpretation of my comment is accurate :)

**Comment by anishasthana** [comment]
@HumairAK I got a +1 from Martin in chat.

**Pull request merged**
