### PR TITLE
Do not instantiate operatorgroup with hashed name

### PR DESCRIPTION
**Pull request by larsks**
The OCS operator creates its own operatorgroup with a hashed name. If
we include the operatorgroup manifest in this repository, that results
in multiple operatorgroups in the namespace, which causes the operator
install to fail.

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
I think we want to keep track of all operator groups. Removing these doesn't seem like a good solution to me. Let's remove the *hash* from the name instead and cleanup the autocreated ones. 
WDYT?

**Comment by larsks** [comment]
@tumido I'm not sure I follow your suggestion exactly: we can't add the operator-group with the unhashed name, because we'll still end up with multiple operator groups.

Is your suggestion to remove the operatorgroup manifest from the `overlay/moc/*/kustomization.yaml`, but keep the `base/operatorgroups/...` manifest around for now even though we're not using it?

**Comment by tumido** [comment]
Nono, I think we should:

- rename the operator group `s/openshift-storage-dsjl6/openshift-storage-operatorgroup/` in git
- deploy our operator group
- if another operator group gets created by the subscription, remove it from the cluster manually

I think upstream has an undocumented name preference. They advise to create the operator group manually for declarative setups as well:
https://github.com/openshift/ocs-operator/blob/e4c49f073e5ccf106b3d7ad7ac3ed73fdae0d078/deploy/deploy-with-olm.yaml

Let's try using the `openshift-storage-operatorgroup` name and see if we get a new group created next time, WDYT?

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
