### PR TITLE
opf-monitoring serviceaccounts, servicemonitors, and namespace migration

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Migrating the serviceaccounts, servicemonitors and namespaces in opf-monitoring to smaug.

Additionally, the pre-commit failed so applying linting to whole AICOE-CI repo.

### CODE REVIEW

**Comment by HumairAK** [comment]
I think breakign `opf-monitoring` into multiple prs is a bit confusing, can you just convert this pr into migrating all of `opf-monitoring` at once to smaug, then close this one? https://github.com/operate-first/apps/pull/1023

**Comment by Gregory-Pereira** [comment]
bump @HumairAK When you get back in are we still doing this? If so is there anything I need to do to unblock this?

**Comment by HumairAK** [comment]
@4n4nd do we need this?

**Pull request closed without merging**
