### PR TITLE
onboard prometheus-anomaly-detector project

### PR DESCRIPTION
**Pull request by 4n4nd**
Resolves https://github.com/operate-first/support/issues/294

### CODE REVIEW

**Review by hemajv — APPROVED** [review]

**Review by tumido — CHANGES_REQUESTED** [review]
you're missing the namespace in the cluster overlay

/hold

**Comment by 4n4nd** [comment]
> you're missing the namespace in the cluster overlay

thanks @tumido! 
updated :+1:

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
