### PR TITLE
Moving cluster-admins to sudoers and removing cluster-admins 

### PR DESCRIPTION
**Pull request by dystewart**
In response to [https://github.com/operate-first/operations/issues/429](https://github.com/operate-first/operations/issues/429)

Moving all cluster-admins over to the sudoers `clusterrole`

### CODE REVIEW

**Comment by larsks** [comment]
In `cluster-scope/overlays/prod/emea/rick/groups/sudoers.yaml`, you have `name: cluster-admins` instead of `name: sudoers`.

**Comment by dystewart** [comment]
@larsks good catch, updated.

**Review by Gregory-Pereira — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
@dystewart see: https://github.com/operate-first/operations/issues/429#issuecomment-1121543326

**Pull request closed without merging**
