### PR TITLE
update to latest ray nightly wheel, update RayCluster CRD

### PR DESCRIPTION
**Pull request by erikerlandson**
addresses https://github.com/operate-first/support/issues/254

### CODE REVIEW

**Comment by erikerlandson** [comment]
cc @HumairAK @tumido

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve
/lgtm

**Comment by tumido** [comment]
@erikerlandson now it is :slightly_smiling_face:

**Pull request merged**
