### PR TITLE
Add ArgoCD Metrics Dashboard

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Review by tumido — APPROVED** [review]
:heart:

**Review by 4n4nd — APPROVED** [review]

**Comment by 4n4nd** [comment]
@harshad16 this PR was merged even though the pre-commit tests failed

**Comment by harshad16** [comment]
> @harshad16 this PR was merged even though the pre-commit tests failed

we haven't made the passing checks default. if we want that to be the default for all projects of operate-first, please do let us know, we can make that change.

**Comment by anishasthana** [comment]
I think making the passing checks default is a good idea. @HumairAK @tumido whaddya think?

**Comment by tumido** [comment]
I agree, let's make it default :+1:

**Pull request merged**
