### PR TITLE
Onboard sigstore to zero cluster.

### PR DESCRIPTION
**Pull request by HumairAK**
Resolve: https://github.com/operate-first/support/issues/245

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
added another user as per user's request

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve

**Review by 4n4nd — APPROVED** [review]

**Pull request merged**
