### PR TITLE
feat(slack-first): Enable github issues to be assigned to oncall

### PR DESCRIPTION
**Pull request by tumido**
Slack first bot can now assign issues on GitHub.

It listens for events on issues acts on:
- added label `bot/assign-on-call`
- comment `/assign-on-call`

Additionally the create issue modal in slack has a checkbox to assign issue to on call member on issue creation. 

/hold

wait for bot release

Example: https://github.com/tumido/slack-first/issues/129

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
bot release was published

/unhold

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
