### PR TITLE
feat(dashboards): Add Kubeflow Pipelines - Tekton user perspective dashboard

### PR DESCRIPTION
**Pull request by tumido**
Dashboard for KFP Tekton user view and profiling

screencapture-grafana-route-opf-monitoring-apps-zero-massopen-cloud-d-2ZPZ1LrGz-kubeflow-pipelines-tekton-user-perspective-2021-06-02-17_42_02

/cc @4n4nd

### CODE REVIEW

**Comment by HumairAK** [comment]
/lgtm
:tada:

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
