### PR TITLE
connect infra cluster to nfs server

### PR DESCRIPTION
**Pull request by larsks**
this commit adds the democratic-csi driver to the infra cluster along
with the appropriate network configuration to access the NFS vlan.

### CODE REVIEW

**Comment by larsks** [comment]
Put on /hold right now because I'm trying to work out some kinks with the physical network configuration.

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
