### PR TITLE
update oauth client secret for devconfus2021 cluster

### PR DESCRIPTION
**Pull request by 4n4nd**
Part of #943

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
Sorry @4n4nd , my changes didn't get saved in sops... Actually we want the UUID in this secret and change it in the `KeycloakClient` (I've copy pasted the `KeycloackClient` from Curator cluster - they both have the same secret there which should not be the case - please take the client secret in this oauth secret resource as the truth and change it in keycloak client.

My bad, sorry.

**Comment by 4n4nd** [comment]
updated :+1:

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
Merging without CI

**Pull request merged**
