### PR TITLE
Add JH PVC manifests that were previously applied manually

### PR DESCRIPTION
**Pull request by 4n4nd**
These PVCs were manually expanded earlier when we did not have secrets management set up.

cc @tumido

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
I think you forgot to list the resources in `kustomization.yaml`

**Comment by tumido** [comment]
@4n4nd I think you need to rebase - move the files from `odh/overlays/moc/jupyterhub` to `odh/overlays/moc/zero/jupyterhub`

**Review by tumido — CHANGES_REQUESTED** [review]
^

**Comment by 4n4nd** [comment]
> @4n4nd I think you need to rebase - move the files from `odh/overlays/moc/jupyterhub` to `odh/overlays/moc/zero/jupyterhub`

@tumido updated :+1:

**Review by tumido — COMMENTED** [review]
/lgtm

`oc diff` looks good, compared to the live manifests, nothing seems to be missing

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
Changes applied, can confirm, no new changes introduced :)

**Pull request merged**
