### PR TITLE
Enable installing strimzi operator on rick

### PR DESCRIPTION
**Pull request by harshad16**
Related https://github.com/operate-first/support/issues/394
Enable installing strimzi operator on rick
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by harshad16** [comment]
@4n4nd  should i restrict it to namespace: opf-kafka

**Comment by 4n4nd** [comment]
> @4n4nd should i restrict it to namespace: opf-kafka

actually yes please, could you also add the kustomization for `opf-kafka` namespace?

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
