### PR TITLE
Add osc owners to osc overlays.

### PR DESCRIPTION
**Pull request by HumairAK**
Resolve: https://github.com/operate-first/support/issues/479

### CODE REVIEW

**Review by erikerlandson — APPROVED** [review]

**Comment by erikerlandson** [comment]
@HumairAK  lgtm
according to sesheta up above we may also want to add vincent and mikhail as org members, but I assume that is a github invite separate from this pr

**Comment by erikerlandson** [comment]
sesheta you aren't the boss of me.

**Comment by HumairAK** [comment]
@caldeirav was invited to the org (on a different timezone), he will accept the invitation tonight

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
