### PR TITLE
removing kepler-edge from argocd and OS-C Cluster1

### PR DESCRIPTION
**Pull request by redmikhail**
Demo project kepler-edge has been completed , decommissioning resources that were used for the project and removing corresponding ArgoCD application and project . FYI @husky-parul

### CODE REVIEW

**Comment by redmikhail** [comment]
@tumido can you please review this PR as it also removes application from ArgoCD for correctness and provide your approval is everything correct?

**Review by tumido — APPROVED** [review]
/lgtm
/approve

@redmikhail manifests look good! :slightly_smiling_face:  Once merged please make sure things get properly deleted by ArgoCD. I'm not sure about the default prune setting and I don't have access to OSClimate clusters to verify that things got properly deleted.

**Pull request merged**
