### PR TITLE
wire up ray cluster CRD into kustomize overlays

### PR DESCRIPTION
**Pull request by erikerlandson**
The portion of https://github.com/operate-first/support/issues/102 that addresses the ray cluster CRD

### CODE REVIEW

**Comment by erikerlandson** [comment]
cc @tumido

**Comment by tumido** [comment]
I'm sorry @erikerlandson this was probably a misscomunication on my end here https://github.com/operate-first/support/issues/102#issuecomment-791338447 The first point still applies.

The CRD is the only resource that has to be placed elsewhere than the JupyterHub namespace. We want to track the resources available to all users (which any custom resource definition is) to be available on a plain sight. If it doesn't come from an operator subscription, it has to be placed here:

https://github.com/operate-first/apps/tree/master/cluster-scope/base/crds

Can you please move it in there?

And then reference the resource in `kustomization.yaml` for the given cluster (`zero` now):
https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/zero/kustomization.yaml#L19

For further info see:
https://github.com/operate-first/blueprint/blob/main/docs/adr/0009-cluster-resources.md
https://github.com/operate-first/apps/blob/master/cluster-scope/README.md

**Review by tumido — CHANGES_REQUESTED** [review]
See above

**Comment by erikerlandson** [comment]
@tumido this didn't merge for some reason

**Comment by tumido** [comment]
@erikerlandson yeah it did not, because our CI is running on the cluster that is currently down :man_facepalming: 

I can merge it manually once we have a cluster to actually deploy this on. :slightly_smiling_face:

**Comment by HumairAK** [comment]
CRD was added to zero cluster: 
```
$ kubectl api-resources --namespaced=true  | grep RayCluster
rayclusters                                                                  cluster.ray.io                               true         RayCluster

```

**Pull request merged**
