### PR TITLE
feat: Add Pulp via OLM

### PR DESCRIPTION
**Pull request by tumido**
Deploy via OLM from a custom catalog. Catalog definition here: https://github.com/tumido/olm-catalog

Resolves: https://github.com/operate-first/support/issues/176
Competition PR: https://github.com/operate-first/apps/pull/663

/hold until it's decided which way (this or the competition PR) is more maintainable for the Pulp team

### CODE REVIEW

**Comment by tumido** [comment]
/unhold

I've verified we can upgrade the operator this way just fine, see https://github.com/tumido/olm-catalog

ready to be reviewed. cc @HumairAK @4n4nd

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm

**Pull request merged**
