### PR TITLE
remove deployment of Thoth's traige party

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Comment by tumido** [comment]
Please make sure the resources are pruned by ArgoCD, I believe it's not enabled by default.

**Comment by goern** [comment]
@tumido I cant :/

```
Unable to delete application: permission denied: applications, delete, thoth/prod-thoth-triage-party-smaug, sub: CiQyNDViNjU2Mi01MzIxLTQyOTUtYTQ1NC1kOGIxZTQwOTVkOTgSCW9wZW5zaGlmdA, iat: 2022-12-01T14:35:50Z
```

**Comment by tumido** [comment]
Oh.. Sorry. I did it then. :slightly_smiling_face:

**Pull request merged**
