### PR TITLE
Move argocd from cd repo to apps 

### PR DESCRIPTION
**Pull request by HumairAK**
Part of: https://github.com/operate-first/continuous-deployment/issues/113 

PR is split in to 3 commits: 

Commit 5b14325:  Just copy pastes all the manifests from [here](https://github.com/operate-first/continuous-deployment/tree/master/manifests), few notes: 
- `crds` folder is removed, and the cluster rbac from [here](https://github.com/operate-first/continuous-deployment/blob/master/manifests/overlays/moc-infra/kustomization.yaml) is removed, these are introduced in the next commit. 

Commit e8421b1: Adds the cluster resources from the following locations to the cluster-scope infra app: [1](https://github.com/operate-first/continuous-deployment/blob/master/manifests/overlays/moc-infra/kustomization.yaml#L6), [2](https://github.com/operate-first/continuous-deployment/blob/master/manifests/overlays/moc-infra/kustomization.yaml#L7)

Commit 32ccb62: Minor change to the pre-commit config to ignore argocd config files. 

PR is a lot bigger than it seems.

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

That's a huge copypaste :smile:

**Review by 4n4nd — APPROVED** [review]
/lgtm
One less repo for us :partying_face:

**Comment by HumairAK** [comment]
pls sesheta

**Pull request merged**
