### PR TITLE
add user to list of Grafana editors

### PR DESCRIPTION
**Pull request by sostrades-radouanbouadel**

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by tumido — CHANGES_REQUESTED** [review]
can you please squash the commits? We'd like to keep the git history tidy.

**Comment by redmikhail** [comment]
@sostrades-radouanbouadel sostrades team should already have access to the Grafana on OS Climate clusters as result of  https://github.com/operate-first/apps/pull/2669 , do you still need this PR ?

**Comment by sostrades-radouanbouadel** [comment]
hello; 
already have access to the Grafana. thanks to Michael all is OK.

**Pull request closed without merging**
