### PR TITLE
Add okd-wg group

### PR DESCRIPTION
**Pull request by LorbusChris**
Adds a group for use by the OKD Working Group (includes both Red Hatters, and non-Red Hatters)

/cc @durandom 

/cc @aleskandro
/cc @bdlink
/cc @binnes
/cc @cheesesashimi
/cc @dmueller2001
/cc @JaimeMagiera
/cc @lmzuccarelli
/cc @LorbusChris
/cc @sandrobonazzola
/cc @sherine-k
/cc @travier
/cc @vrutkovs

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Review by travier — APPROVED** [review]

**Review by aleskandro — APPROVED** [review]

**Comment by durandom** [comment]
/ok-to-test

@Gregory-Pereira can you review this?

**Review by Gregory-Pereira — COMMENTED** [review]
Everything looks great, only curious why we have two open PRs that do the same thing, [see duplicate](https://github.com/operate-first/apps/pull/2192).
/lgtm

**Comment by durandom** [comment]
> Everything looks great, only curious why we have two open PRs that do the same thing, [see duplicate](https://github.com/operate-first/apps/pull/2192). /lgtm

It's actually two different teams :) one for the OKD working group and one for the core team

**Comment by HumairAK** [comment]
at the moment these groups are not really being added to any clusters, is this intentional? will there be an okd cluster being added at some point? (might be out of the loop on this one)

**Comment by durandom** [comment]
These groups will have access to namespaces and other resources. PRs coming

**Pull request merged**
