### PR TITLE
Add external urls flag for Prometheus and Alertmanager

### PR DESCRIPTION
**Pull request by 4n4nd**
Closes https://github.com/operate-first/SRE/issues/121

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by hemajv — APPROVED** [review]
/lgtm
@4n4nd thanks for the quick fix! :+1:

**Review by tumido — APPROVED** [review]
/approve

**Comment by HumairAK** [comment]
Rebase please : )

**Comment by harshad16** [comment]
> any idea why are 2 bots adding 2 different `needs-rebase` labels and only one is removed once rebased? Why are 2 bots competing on this?

thanks for bring this my notice. 
the sefkhet-abwy was earlier designed to check on rebases, with the new prow, that feature comes along, so we can deprecate it from the sefkhet-abwy. i will open a issue on our side for this.

**Pull request merged**
