### PR TITLE
Add pachyderm osc admin group.

### PR DESCRIPTION
**Pull request by HumairAK**
Set up a group that has admin access to the pachyderm namespace within the osc-cl2 cluster.

Also added a commit to update the pachyderm resource as the operator does not accept the metrics field. 

Also added owners file with osc contributors.

### CODE REVIEW

**Review by Gregory-Pereira — COMMENTED** [review]
/lgtm
Only question is can we / should we have multiple `OWNERS` files in our repository?

**Comment by HumairAK** [comment]
@Gregory-Pereira yes

**Comment by caldeirav** [comment]
Ultimately we want a single osc-admin group that has admin rights for pachyderm, trino, superset and all future components of the data platform. Is this the path we are taking?

**Comment by HumairAK** [comment]
@Gregory-Pereira can you re-review

**Comment by HumairAK** [comment]
@caldeirav I'll create the issue and clarify terms/etc so that we can hash out what sort of groups we should have.

**Review by dystewart — APPROVED** [review]
/lgtm

**Pull request merged**
