### PR TITLE
overlays/infra: Increase system reserved memory for worker nodes

### PR DESCRIPTION
**Pull request by larsks**
This is the same as #673, but for the moc-infra cluster.

Part of #671.

### CODE REVIEW

**Comment by larsks** [comment]
Reminder that merging this will cause a cluster reboot.

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve
/lgtm

**Comment by tumido** [comment]
@larsks @4n4nd we can unhold whenever ready. I don't think we should see any problems with node restarts on infra so the impact should be minimal - yet we should announce an possible outage.

**Comment by tumido** [comment]
Resolves: https://github.com/operate-first/apps/issues/671

**Review by 4n4nd — APPROVED** [review]

**Pull request merged**
