### PR TITLE
Update group.yaml

### PR DESCRIPTION
**Pull request by raz-mon**
Adding raz-mon username to the list of users.

### CODE REVIEW

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm
/approve

**Comment by Gregory-Pereira** [comment]
A breaking change was introduced earlier and then fixed, if you rebase your pr should pass.

**Comment by Gregory-Pereira** [comment]
> Sorry I merged it instead of rebasing. Will the PR still pass or should I open a new one?

I am not seeing that this got merged, unless you made it as a new PR. I think its still open and if that is the case it should be rebaseable. In anycase its not a breaking change, and there aren't any conflicts so Im not sure its an issue.

**Comment by raz-mon** [comment]
OK great, so should I do something else, or just wait for your approval?

Thanks.

**Comment by Gregory-Pereira** [comment]
If It hasn't merged yet you may need to rebase. I'm going to run a re-test to see if it passes the checks now that we fixed the issue. If it doesn't then just rebase your PR and you will be good to go.
/retest

**Comment by durandom** [comment]
@raz-mon  can we get a 👍  from anybody of your team?

**Comment by raz-mon** [comment]
Sure.

**Comment by ilya-kolchinsky** [comment]
Hi @durandom, does my 👍 qualify? :)

**Comment by 4n4nd** [comment]
@raz-mon the changes should be applied and you should have access to the project now

**Comment by raz-mon** [comment]
Great, many thanks.

**Pull request merged**
