### PR TITLE
Update Fybrik manifests to new release

### PR DESCRIPTION
**Pull request by revit13**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by HumairAK** [comment]
Hrmm not sure why ci is failing, logs showing: 
```
 Aborting due to errexit on line 45. Exit code: 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-08-07T19:08:21Z"} 
```

Trying again.

/test kubeval-validation

**Comment by HumairAK** [comment]
@mimotej / @harshad16  / @Gregory-Pereira  -- any idea why this is failing? I just see the error above and that's it.

**Comment by mimotej** [comment]
> @mimotej / @harshad16 / @Gregory-Pereira -- any idea why this is failing? I just see the error above and that's it.

@HumairAK Kubeval validation when it's not using color can be quite a mess but this error is valid. Actual error is shown here: 
image

`creationTimestamp: null` should not be used in CRDs, this value is generated by controller and should not be used by users. 
Here it is explained in detail: 
image
These are lines from [_definitions.json file](https://github.com/operate-first/schema-store/blob/main/schemas/master-standalone-strict/_definitions.json) sadly file is too big so i can link the line here. I am not familiar with fybrik so I am not sure how this PR was exactly generated, but these `creationTimestamp`s should be omited.

I am thinking how we could make kubeval output more readable by default kubeval uses colors to show what is correct and what is not (it also can be forced to use colors even when there is not TTY used, but I am not sure if prows output supports colors. @harshad16 do you know if this would work with prow? 
I currently when I am looking at kubeval output look in the end and check last overlay tested and I am looking for WARN or ERR in the output.
There are two types of WARN:
1) Ending with `was not validated against a schema` - These warnings are not causing errors but still are worth checking if somebody for example didn't spell `kind` wrong.
2) Rest of the warnings (for example these on the image on the top) are warning which are propably causing the script to fail.
Hopefully I have clarified this little bit if you have any questions feel free to ask :)

**Comment by harshad16** [comment]
Seems like it prow support ANSI color https://github.com/kubernetes/test-infra/issues/15261, anyhow I would suggest trying the use of color and let's see what happens. we haven't invested any time in the details of prow logging.

**Comment by HumairAK** [comment]
@revit13 / @roytman can these `creationTimestamp` values be removed from the generation as per above?

**Comment by roytman** [comment]
Hi @Mohammad-nassar10 , could you please check it

**Comment by roytman** [comment]
@HumairAK did you change something in operate-first environment validation? These `creationTimestamp` values were part of all previous Fybrik commits, and we use the same CRD yaml files in our tests, and we don't get any errors related to the fields. 
The values are generated by kubebuilder, the issue was mentioned by  https://github.com/kubernetes-sigs/controller-tools/issues/402 , but has not been resolved yet.

**Comment by HumairAK** [comment]
> did you change something in operate-first environment validation? 

@roytman yes, this is a result of recently adding [kubeval](https://github.com/instrumenta/kubeval) validation to our CI, to ensure manifests are checked against OCP openapi spec and are valid before merging.

**Comment by roytman** [comment]
Hi @HumairAK we have updated our build process and removed these `creationTimestamp` fields. This PR will be updated soon. 
However, I wanted to include `kubeval` into our pipeline too, looks like `kubeval` doesn't support validation of CRDs (there are several issues / discussions about it). 
Can you point me to your `kubeval` configuration ?

**Comment by HumairAK** [comment]
@roytman , the script that runs: https://github.com/operate-first/toolbox/blob/master/scripts/test-kubeval-validation#L45 
Schema store: https://raw.githubusercontent.com/operate-first/schema-store/main/schemas

We store schemas in the location above and validate against it. @mimotej can clarify further if needed, as he set this up. 

Some more discussion on this topic: 
* https://github.com/operate-first/operations/issues/107
* https://github.com/operate-first/toolbox/pull/81

**Comment by roytman** [comment]
Hi @HumairAK , the tests've passed.

**Comment by HumairAK** [comment]
@roytman awesome, thank you!!

/lgtm
/approve

**Pull request merged**
