### PR TITLE
feat: add Apicurio to viewers on opf-monitoring

### PR DESCRIPTION
**Pull request by paoloantinori**
I've mimicked this PR: https://github.com/operate-first/apps/pull/593/files

What I'm after is: getting access to the Apicurio team members to Graphana and Prometheus

### CODE REVIEW

**Comment by 4n4nd** [comment]
@paoloantinori Can you please update [this existing rolebinding](https://github.com/operate-first/apps/blob/master/kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml#L14) instead of creating a new one? This way we can manage who has access from one place.

Sorry about the missing docs for this

**Comment by paoloantinori** [comment]
No problem, updated my PR!

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
