### PR TITLE
feat: Onboard moc-reporting

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/support/issues/169

@rob-baron this PR creates the `moc-reporting` namespace for you, a user group `moc-reporting` with you included. It also removes you from the `cluster-admins` group while adding you to `cluster-logs-readers`. Are there any additional permissions you'd need for your project?

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Comment by tumido** [comment]
Issue resolved itself with migration to Smaug

**Pull request closed without merging**
