### PR TITLE
Modifying osc-cl2 trino config properties

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Removing `oauth2.auth-url`, `oauth2.token-url`, `oauth2.jwks-url`, upping log level to debug and setting Oauth2 as authentication type

Signed-off-by: greg pereira <grpereir@redhat.com>

/cc @erikerlandson

### CODE REVIEW

**Review by erikerlandson — APPROVED** [review]

**Comment by Gregory-Pereira** [comment]
Argocd sync for `kfdefs/overlays/osc/osc-cl2` has been disabled, deploying changes to trino manually.

**Comment by HumairAK** [comment]
based on slack discussions I understand we don't need this anymore closing, please re-open (or create a new pr) if this is still required

**Pull request closed without merging**
