### PR TITLE
JH add override to ignore internal cert validation

### LINKED ISSUE #240: Override Jupyterhub Configmap to add a workaround for validating certs
To reflect the change made live during the JH image update to resolve the issue mentioned [here](https://github.com/operate-first/apps/issues/231#issuecomment-776806628), we will need to override the configmap and add the following line to `jupyterhub-cfg` configmap for `jupyterhub_config.py` : 

 jupyterhub_config.py: c.OpenShiftOAuthenticator.validate_cert = False

### PR DESCRIPTION
**Pull request by 4n4nd**
Closes #240

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
whelp: 

```
 time="2021-02-11T15:13:03Z" level=warning msg="Encountered error applying application jupyterhub:  (kubeflow.error): Code 500 with message: Apply.Run : error when applying patch:\n{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"PersistentVolumeClaim\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"kfctl.kubeflow.io/kfdef-instance\\\":\\\"opendatahub.opf-jupyterhub\\\"},\\\"labels\\\":{\\\"component.opendatahub.io/name\\\":\\\"jupyterhub\\\",\\\"opendatahub.io/component\\\":\\\"true\\\"},\\\"name\\\":\\\"jupyterhub-db\\\",\\\"namespace\\\":\\\"opf-jupyterhub\\\"},\\\"spec\\\":{\\\"accessModes\\\":[\\\"ReadWriteOnce\\\"],\\\"resources\\\":{\\\"requests\\\":{\\\"storage\\\":\\\"1Gi\\\"}}}}\\n\",\"volume.beta.kubernetes.io/storage-class\":null}}}\nto:\nResource: \"/v1, Resource=persistentvolumeclaims\", GroupVersionKind: \"/v1, Kind=PersistentVolumeClaim\"\nName: \"jupyterhub-db\", Namespace: \"opf-jupyterhub\"\nObject: &{map[\"apiVersion\":\"v1\" \"kind\":\"PersistentVolumeClaim\" \"metadata\":map[\"annotations\":map[\"kfctl.kubeflow.io/kfdef-instance\":\"opendatahub.opf-jupyterhub\" \"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"PersistentVolumeClaim\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"kfctl.kubeflow.io/kfdef-instance\\\":\\\"opendatahub.opf-jupyterhub\\\",\\\"volume.beta.kubernetes.io/storage-class\\\":\\\"ocs-storagecluster-cephfs\\\"},\\\"labels\\\":{\\\"component.opendatahub.io/name\\\":\\\"jupyterhub\\\",\\\"opendatahub.io/component\\\":\\\"true\\\"},\\\"name\\\":\\\"jupyterhub-db\\\",\\\"namespace\\\":\\\"opf-jupyterhub\\\"},\\\"spec\\\":{\\\"accessModes\\\":[\\\"ReadWriteOnce\\\"],\\\"resources\\\":{\\\"requests\\\":{\\\"storage\\\":\\\"1Gi\\\"}}}}\\n\" \"pv.kubernetes.io/bind-completed\":\"yes\" \"pv.kubernetes.io/bound-by-controller\":\"yes\" \"volume.beta.kubernetes.io/storage-class\":\"ocs-storagecluster-cephfs\" \"volume.beta.kubernetes.io/storage-provisioner\":\"openshift-storage.cephfs.csi.ceph.com\"] \"creationTimestamp\":\"2020-11-12T18:57:20Z\" \"finalizers\":[\"kubernetes.io/pvc-protection\"] \"labels\":map[\"component.opendatahub.io/name\":\"jupyterhub\" \"opendatahub.io/component\":\"true\"] \"managedFields\":[map[\"apiVersion\":\"v1\" \"fieldsType\":\"FieldsV1\" \"fieldsV1\":map[\"f:metadata\":map[\"f:annotations\":map[\"f:pv.kubernetes.io/bind-completed\":map[] \"f:pv.kubernetes.io/bound-by-controller\":map[] \"f:volume.beta.kubernetes.io/storage-provisioner\":map[]]] \"f:spec\":map[\"f:volumeName\":map[]] \"f:status\":map[\"f:accessModes\":map[] \"f:capacity\":map[\".\":map[] \"f:storage\":map[]] \"f:phase\":map[]]] \"manager\":\"kube-controller-manager\" \"operation\":\"Update\" \"time\":\"2020-11-12T18:57:23Z\"] map[\"apiVersion\":\"v1\" \"fieldsType\":\"FieldsV1\" \"fieldsV1\":map[\"f:metadata\":map[\"f:annotations\":map[\".\":map[] \"f:kfctl.kubeflow.io/kfdef-instance\":map[] \"f:kubectl.kubernetes.io/last-applied-configuration\":map[] \"f:volume.beta.kubernetes.io/storage-class\":map[]] \"f:labels\":map[\".\":map[] \"f:component.opendatahub.io/name\":map[] \"f:opendatahub.io/component\":map[]]] \"f:spec\":map[\"f:accessModes\":map[] \"f:resources\":map[\"f:requests\":map[\".\":map[] \"f:storage\":map[]]] \"f:volumeMode\":map[]]] \"manager\":\"opendatahub-operator\" \"operation\":\"Update\" \"time\":\"2020-11-16T14:42:29Z\"]] \"name\":\"jupyterhub-db\" \"namespace\":\"opf-jupyterhub\" \"resourceVersion\":\"8797105\" \"selfLink\":\"/api/v1/namespaces/opf-jupyterhub/persistentvolumeclaims/jupyterhub-db\" \"uid\":\"1109f31f-65c9-4772-962f-0db137a834ff\"] \"spec\":map[\"accessModes\":[\"ReadWriteOnce\"] \"resources\":map[\"requests\":map[\"storage\":\"1Gi\"]] \"volumeMode\":\"Filesystem\" \"volumeName\":\"pvc-1109f31f-65c9-4772-962f-0db137a834ff\"] \"status\":map[\"accessModes\":[\"ReadWriteOnce\"] \"capacity\":map[\"storage\":\"1Gi\"] \"phase\":\"Bound\"]]}\nfor: \"/tmp/kout766847170\": PersistentVolumeClaim \"jupyterhub-db\" is invalid: metadata.annotations.volume.beta.kubernetes.io/storage-class: Invalid value: \"\": field is immutable"
```

**Comment by tumido** [comment]
Yes, we knew this would remove the storage class.. though we didn't anticipate it being a problem... We need to bring it back probably. While the storage class effectively stays the same, the only way to migrate this is to manually provision a  new one (without storage class set) and migrate the data manually.

**Pull request merged**
